   <div class="features">
		<div class="section-wrapper">
			<div id="" class="sub-section">
				<div>
					<div class="image"></div>
					<div class="text">
						<p class="into"></p>
						<p></p>
						<span class="button"></span>
					</div>
				</div>
				
				<div class="section-info">
					<div class="info-text">
						<h2></h2>
					</div>
					<div class="info-links">					
					</div> 
				</div>
			</div>
		</div>
	</div>
	<div class="features-nav">
		<ul>
			<li>
				<a>
					<img />
					<span></span>				
				</a>
			</li>
		</ul>
	</div>