		
        <div id="left-section"> 
			<div id="search-tabs">
				<ul>
					<li><a href="#search-1">page-1</a></li>
				</ul>
				<div id="search-1">search result</div>
			</div>	
			<div class="result-pager ui-corner-all ui-widget-content" style="display:none">
				<span id="doc-pager"></span>
			</div> 
		</div>
		
		<div id="right-section" class="ui-widget-content ui-corner-all"> 
		   <label class="search">Search Filters</label>
			<?php echo $this->searchForm; 
				echo $this->inlineScript()->setScript('jQuery(function () { rms.initSearch(); })'); 
			?>		
		</div>