<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Help_Model_HelpCategory', 'con1');

/**
 * Help_Model_Base_HelpCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $Documents
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class Help_Model_Base_HelpCategory extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('help_category');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Help_Model_HelpDocument as Documents', array(
             'local' => 'id',
             'foreign' => 'help_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}