<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Help_Model_HelpTemplate', 'con1');

/**
 * Help_Model_Base_HelpTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $note
 * @property Doctrine_Collection $HelpField
 * @property Doctrine_Collection $HelpBoilerPlate
 * @property Doctrine_Collection $Plates
 * @property Doctrine_Collection $Layout
 * @property Doctrine_Collection $TemplateFields
 * @property Doctrine_Collection $Documents
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class Help_Model_Base_HelpTemplate extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('help_template');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Help_Model_HelpField as HelpField', array(
             'refClass' => 'Help_Model_HelpTemplateField',
             'local' => 'help_template_id',
             'foreign' => 'help_field_id'));

        $this->hasMany('Help_Model_HelpBoilerPlate as HelpBoilerPlate', array(
             'refClass' => 'Help_Model_HelpTemplateBoilerPlate',
             'local' => 'help_template_id',
             'foreign' => 'help_boiler_plate_id'));

        $this->hasMany('Help_Model_HelpTemplateBoilerPlate as Plates', array(
             'local' => 'id',
             'foreign' => 'help_template_id'));

        $this->hasMany('Help_Model_HelpTemplateLayout as Layout', array(
             'local' => 'id',
             'foreign' => 'help_template_id'));

        $this->hasMany('Help_Model_HelpTemplateField as TemplateFields', array(
             'local' => 'id',
             'foreign' => 'help_template_id'));

        $this->hasMany('Help_Model_HelpType as Documents', array(
             'local' => 'id',
             'foreign' => 'help_template_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}