<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Help_Model_HelpDocument', 'con1');

/**
 * Help_Model_Base_HelpDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keyword
 * @property clob $content
 * @property string $answer
 * @property string $related_item
 * @property string $question
 * @property integer $module
 * @property integer $help_type_id
 * @property integer $help_category_id
 * @property integer $role_id
 * @property integer $admin_group_id
 * @property Help_Model_HelpCategory $HelpCategory
 * @property Help_Model_HelpType $HelpType
 * @property Help_Model_Role $Role
 * @property Help_Model_AdminGroup $AdminGroup
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class Help_Model_Base_HelpDocument extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('help_document');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('keyword', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('answer', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('related_item', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('question', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('module', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('help_type_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('help_category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('admin_group_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Help_Model_HelpCategory as HelpCategory', array(
             'local' => 'help_category_id',
             'foreign' => 'id'));

        $this->hasOne('Help_Model_HelpType as HelpType', array(
             'local' => 'help_type_id',
             'foreign' => 'id'));

        $this->hasOne('Help_Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasOne('Help_Model_AdminGroup as AdminGroup', array(
             'local' => 'admin_group_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'content',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'content',
              1 => 'title',
              2 => 'description',
              3 => 'keyword',
             ),
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($versionable0);
        $this->actAs($searchable0);
        $this->actAs($sluggable0);
        $this->actAs($softdelete0);
    }
}