<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Help_Model_HelpField', 'con1');

/**
 * Help_Model_Base_HelpField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $label
 * @property string $description
 * @property integer $is_mandatory
 * @property integer $is_searchable
 * @property Doctrine_Collection $Layout
 * @property Doctrine_Collection $Templates
 * @property Doctrine_Collection $TemplateFields
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class Help_Model_Base_HelpField extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('help_field');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('label', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_mandatory', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('is_searchable', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Help_Model_HelpTemplateLayout as Layout', array(
             'local' => 'id',
             'foreign' => 'help_field_id'));

        $this->hasMany('Help_Model_HelpTemplate as Templates', array(
             'refClass' => 'Help_Model_HelpTemplateField',
             'local' => 'help_field_id',
             'foreign' => 'help_template_id'));

        $this->hasMany('Help_Model_HelpTemplateField as TemplateFields', array(
             'local' => 'id',
             'foreign' => 'help_field_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}