<?php /* This file encoded by Raizlabs PHP Obfuscator http://www.raizlabs.com/software */ ?>
<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Help_Model_TemplateLayout', 'con2');

/**
 * Help_Model_Base_TemplateLayout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $template_id
 * @property integer $section_id
 * @property integer $field_id
 * @property integer $section_seq
 * @property integer $item_seq
 * @property string $content_type
 * @property Help_Model_Field $Field
 * @property Help_Model_Template $Template
 * @property Help_Model_Section $Section
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class Help_Model_Base_TemplateLayout extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('template_layout');
        $this->hasColumn('template_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('section_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('field_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('section_seq', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => '4',
             ));
        $this->hasColumn('item_seq', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => '4',
             ));
        $this->hasColumn('content_type', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Help_Model_Field as Field', array(
             'local' => 'field_id',
             'foreign' => 'id'));

        $this->hasOne('Help_Model_Template as Template', array(
             'local' => 'template_id',
             'foreign' => 'id'));

        $this->hasOne('Help_Model_Section as Section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}