	
 <div id="finder" style="display:none" class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-draggable" tabindex="-1" role="dialog" aria-labelledby="ui-dialog-title-document-finder"><div class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix"  style="-moz-user-select: none;"><span class="ui-dialog-title" id="ui-dialog-title-document-finder"  style="-moz-user-select: none;">Find Related Documents</span><a href="#" id="close-finder" class="ui-dialog-titlebar-close ui-corner-all" role="button"  style="-moz-user-select: none;"><span class="ui-icon ui-icon-closethick"  style="-moz-user-select: none;">close</span></a></div><div style="height: auto; min-height: 104px; width: auto;" id="document-finder" class="ui-dialog-content ui-widget-content">
 		<table width="100%" border="0" class="EditTable finder-table">
  <tbody><tr class="FormData">
    <td width="30%" ui-widget-content" valign="top"><label>Document Type</label></td>
    <td class="DataTD ui-widget-content" valign="top">				
	         <select id="search-type" name="search-type"> 
				<?php	
					foreach($this->doctype as $obj){ ?>
						<option value="<?php echo $obj['id']; ?>"><?php echo $obj['title']; ?></option>
<?php				} ?>
				 
				</select></td>
  </tr>
  <tr class="FormData">
    <td class="ui-widget-content" valign="top"><label>Keyword</label></td>
    <td class="DataTD ui-widget-content" valign="top">
    <textarea id="doc-keyword" name="doc-keyword"></textarea></td>
  </tr>
  <tr>
  	<td colspan="2">
  		<div class="form-info-div">
  		 <ol>
  		 	<li>Select a document type from the drop down list.</li>
  		 	<li>Type keyword in the keyword textarea, a list of matching items would be displayed below the keyword text area.</li>
  		 	<li>Select an item from the list. The selected item would be displayed in the keyword area.</li>
  		 	<li>To search for more items, repeat steps 1-3. Type new keyword after the comma displayed.</li>
  		 	<li>Click 'Apply' to apply the selected items to the document.</li>
  		 </ol>
  		</div>
  	</td>
  </tr>
  <tr>
    <td align="right" class="EditButton ui-widget-content" colspan="2"> 
					<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left" id="add-doc" href="#">
					  Apply<span class="ui-icon ui-icon-disk"></span></a>
					<a class="fm-button ui-state-default ui-corner-all fm-button-icon-left" id="close-finder" href="#">
					  Close<span class="ui-icon ui-icon-close"></span></a>			
	</td>
  </tr>
</tbody></table>
</div></div>