 <div id="layout-shell" title="" style="display:none">     
    <p class="page-desc ui-corner-all ui-widget-content"></p>
 	<div id="layout-items-position"></div>
 	<form action="<?php echo $this->formAction; ?>" method="post" id="layout-form">
 		<input name="template_id" value="" type="hidden" id="frm-template_id"/>
 		<input name="page_id" value="" type="hidden" id="frm-page_id"/>
 		<div id="layout-body" class="ui-widget-content ui-corner-all"></div>
 	</form>
 </div>
 
