	<div id="page-design" class="full-width">
		 	<div id="page-tabs">
				<ul>
						<li><a href="#tabs-1">Order Summary</a></li>
						<li><a href="<?php $param['table']    = 'ecom_order';
											echo $this->url($param, 'grid-index');
								     ?>">Transactions</a></li>
						<li><a href="<?php $param['table'] = 'ecom_order_detail';
										echo $this->url($param, 'grid-index');
								?>">Order Detail</a></li>
						<li><a href="<?php echo $this->url(array('id' => 1), HELP_ROUTE); ?>">Help</a></li>

				</ul>
				<div id="tabs-1">
		 			<?php echo $this->gridData; ?>
		 		</div>
		 	</div>
	</div>