<?php

/**
 * Admin_Model_AddressBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_AddressBook extends Admin_Model_Base_AddressBook
{
	const TYPE_HOME   = 'home';
	const TYPE_OFFICE = 'office' ;
	
	public function __toString(){
		$address = implode(', ', array($this->line1, $this->city, $this->post_code, $this->country));	 
		return $address;
	}
}