<?php

/**
 * Admin_Model_AdminContentType
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_AdminContentType extends Admin_Model_Base_AdminContentType{
	public static function getContentTypes(){
				
		$res = self::getRemoteData(__FUNCTION__, array());
		return $res;
		
/*		$model  = __CLASS__;
	 
		$filter = new Rhema_Dao_Filter();
		$filter->setModel($model)
			   ->addJoin('AdminTable', Rhema_Dao_Filter::INNER_JOIN, array('id', 'title', 'name'))
			   ->addOrderBy('sequence')
			   ->addFields(array('id', 'code', 'title', 'color')); 
		$query = Rhema_Model_Service::createQuery($filter);   
		
		$return  = $query->execute();
 
		return $return ? $return : array();*/
	}

}