<?php

/**
 * Admin_Model_AdminCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_AdminCategory extends Admin_Model_Base_AdminCategory
{
	public static function getCategory(){
		$model = __CLASS__ ;
		$query		= Doctrine_Query::create()
						->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY) 
						->from("$model t INDEXBY t.id");
		return $query->execute();
	}
}