<?php

/**
 * Admin_Model_AdminSetting
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_AdminSetting extends Admin_Model_Base_AdminSetting{

	public static function getSettings(){
		$model = __CLASS__ ;
		$query = Doctrine_Query::create()
					->select('t.name,m.*')
					->from("$model m")
					->leftJoin('m.AdminTable t')
					//->useResultCache(true)
					->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
		return $query->execute();

	}
}