<?php
/**
 * Admin_Model_AdminSubsite
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_AdminSubsite extends Admin_Model_Base_AdminSubsite {
    public static function getSiteDetails($domain, $directory){ 
        		
        $res = self::getRemoteData(__FUNCTION__, array(__CLASS__,  $domain, $directory ));
		return $res;
/*		
        if(Rhema_Util::isHomeDomain()){
            $server = Rhema_Model_Service::factory('Admin_Service_Server', false );
            return $server->getSiteDetails($model, $domain, $directory );
        }else{
            $client = Rhema_Util::getRemoteClient();
            $resp = $client->getSiteDetails($model, $domain, $directory )->get();
            return self::getRestResult($resp, __FUNCTION__ );
        }*/
    }
}