<?php

/**
 * Admin_Model_AdminDictionary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_AdminDictionary extends Admin_Model_Base_AdminDictionary{
	
	public function getFieldlabels(){
		$labels = array();
		$filter = new Rhema_Dao_Filter();
		$filter->addAttribute(array('title', 'label'))->setModel(__CLASS__)->setIndexBy('title');
		
		$result = $this->_setFilters($filter)->fetchArray();
		foreach($result as $field => $data){
			$labels[$data['title']] = $data['label'];
		}
		return $labels;
	}
}