<?php

/**
 * Admin_Model_AdminModule
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_AdminModule extends Admin_Model_Base_AdminModule{

		public static function listAllModules($mode = Doctrine_Core::HYDRATE_ARRAY){
			$res = self::getRemoteData(__FUNCTION__, array(__CLASS__, $mode));
			return $res;
			
/*			if(Rhema_Util::isHomeDomain()){
  				$server = new Admin_Service_Server();
				return $server->listAllModules(__CLASS__, $mode);
			}else{
				$client = Rhema_Util::getRemoteClient();
				$resp   = $client->listAllModules(__CLASS__, $mode)->get();
				return self::getRestResult($resp, __FUNCTION__);
			}*/
		}

		public static function getSiteModules(){
			$siteId  	= Zend_Registry::get('namespace')->subsiteId;			
			$res = self::getRemoteData(__FUNCTION__, array(__CLASS__, $siteId));
			return $res;
			
/*			if(Rhema_Util::isHomeDomain()){
  				$server = new Admin_Service_Server();
				return $server->getSiteModules(__CLASS__,$siteId);
			}else{
				$client 	= Rhema_Util::getRemoteClient();
				$resp   	= $client->getSiteModules(__CLASS__, $siteId)->get();
				return self::getRestResult($resp, __FUNCTION__);
			}*/
		}

		public static function getModuleContent($module){	
			
/*			$res = self::getRemoteData(__FUNCTION__, array(__CLASS__, $module));
			return $res;
*/			
			//if(Rhema_Util::isHomeDomain()){
	  				$server = new Admin_Service_Server();
				return $server->getModuleContent(__CLASS__, $module);
	/*		}else{
				$client = Rhema_Util::getRemoteClient();
				$resp = $client->getModuleContent(__CLASS__, $module)->get();
				
				return self::getRestResult($resp, __FUNCTION__);
			}*/
	}
	public function moduleNavigation($mod = 'cms', $loggedIn = false){
		$root_id = null;
		$isAdmin = true;
		$moduleFound = false;
		$option = array(
				Rhema_Constant::MENU_MODULE => $mod);
		
		$menu = new Admin_Model_AdminMenu(); // Rhema_Model_Service::factory('AdminMenu');
		//$modObject = Rhema_Model_Service::factory('AdminModule');
		$modules = $this->getSiteModules();
		
		foreach($modules as $item){
			if($mod == $item['code']){
				$root_id = $item['admin_menu_id'];
				$option = array(
						'root_id' => $root_id);
				$moduleFound = true;
				$curMod = $item;
				break;
			}
		}
		
		$option = array('root_id' => $root_id);
		$dto = $menu->getMenuTree($option);
		$dto->setModules($modules);
		if($moduleFound){
			$dto->setModuleData($item);
		}
		
		return $dto;
	}
}