<?php

/**
 * Admin_Model_AffiliateBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_AffiliateBanner extends Admin_Model_Base_AffiliateBanner
{
	public function getBanners($width, $height, $limit = 10){ 
    	$daoFilter = new Rhema_Dao_Filter($limit);
    	$daoFilter->setModel(__CLASS__);
    	 
 	    $daoFilter->addCondition('width', $width) 
 	    		  ->addCondition('height', $height)
 	    		  ->addCondition('is_active', 1)
 	    		  //->setDebug(true)
 	    		  ->addOrderBy('id');
 	    //return Rhema_Model_Service::createQuery($daoFilter);		 	  
	    return Rhema_Model_Service::createQuery($daoFilter)->execute(); 		
	}
}