<?php

/**
 * Admin_Model_AffiliateRetailerType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_AffiliateRetailerType extends Admin_Model_Base_AffiliateRetailerType
{
	public static function getRetailerType($value, $fieldName = 'slug'){
		return Doctrine_Core::getTable(__CLASS__)->findOneBy($fieldName, $value, Doctrine_Core::HYDRATE_ARRAY);
	}
}