<?php

/**
 * Admin_Model_AffiliateProductBrand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_AffiliateProductBrand extends Admin_Model_Base_AffiliateProductBrand
{
	
	public static function listBrands($prefix = null){
    	$daoFilter = new Rhema_Dao_Filter();
    	$daoFilter->setModel(__CLASS__) 
    	          ->addFields(array('id', 'title', 'description', 'keywords', 'slug'))
    			  ->addOrderBy('sort_order',  Rhema_Dao_Filter::ORDER_DESC) 
    	          ->setOrderBy('title');
    	          
    	if('0-9' == $prefix){
	    	for($i=0; $i<=9; $i++){
	    		$daoFilter->addCondition('title', $i, Rhema_Dao_Filter::OP_LLIKE,Rhema_Dao_Filter::OP_OR);
	    	}
    	}else if($prefix){
    		$daoFilter->addCondition('title', $prefix, Rhema_Dao_Filter::OP_LLIKE);
    	}	
    		  
    	return Rhema_Model_Service::createQuery($daoFilter)->execute();		
	}
	
	public function getBrand($id, $key = 'id'){
		$filter = new Rhema_Dao_Filter();
		$filter->setModel(__CLASS__)
			   ->addCondition($key, $id);
		return Rhema_Model_Service::createQuery($filter)->fetchOne();		
	}
	
	
	public function countProductsByBrand(){
    	$daoFilter = new Rhema_Dao_Filter();
    	$daoFilter->setModel(__CLASS__) 
    			  ->addJoin('AffiliateProduct', Rhema_Dao_Filter::INNER_JOIN, array('id'))
    			  ->addFields(array('id', 'title', 'slug'))
    			  ->addGroupBy('id')
    			  //->setDebug(true)
    			  ->addOrderBy('title')
    			  ->addAggregateFieldList('AffiliateProduct.id', 'COUNT');
		  
    	return Rhema_Model_Service::createQuery($daoFilter)->execute();
	}
	
	public function getKeywords(){
    	$daoFilter = new Rhema_Dao_Filter();
    	$daoFilter->setModel(__CLASS__)
    			  ->addCondition('keywords', null, Rhema_Dao_Filter::OP_NOT_NULL)
    			  ->addFields(array('keywords')) ;   			 			   	  
    	return Rhema_Model_Service::createQuery($daoFilter)->execute()		;
	}
}