<?php

/**
 * Admin_Model_AffiliateFeed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_AffiliateFeed extends Admin_Model_Base_AffiliateFeed
{
 
	/**
	 * Enter description here ...
	 * @param unknown_type $codesOnly
	 * @return Ambigous <Doctrine_Collection, mixed, PDOStatement, Doctrine_Adapter_Statement, Doctrine_Connection_Statement, unknown, number>
	 */
	public function getFeedList($codesOnly = false){
		$daoFilter = new Rhema_Dao_Filter();
		$daoFilter->setModel(__CLASS__)
				  ->addCondition('is_active', 1)
				  ->setIndexBy('id')
				  ->addFields(array('feed_url', 'id', 'title', 'affiliate_feed_type_id'))
				  ->addCondition('is_active', 1, Rhema_Dao_Filter::OP_EQ)
				  ->addCondition('feed_url', null, Rhema_Dao_Filter::OP_NOT_NULL);
		if($codesOnly){
			$daoFilter->addCondition('title', 'codes', Rhema_Dao_Filter::OP_LRLIKE);
		}
		return Rhema_Model_Service::createQuery($daoFilter)->execute();
	}
	
	public function getFeedDataById($id, $mode = Doctrine_Core::HYDRATE_RECORD){
		$daoFilter = new Rhema_Dao_Filter();
		$daoFilter->setModel(__CLASS__)
				  ->addCondition('id', $id)
				  ->setHydrationMode($mode) 
				  ->addJoin('AffiliateNetwork', Rhema_Dao_Filter::INNER_JOIN, 'field_mapping')
				  ->setIndexBy('id') ;
		return Rhema_Model_Service::createQuery($daoFilter)->fetchOne();
	}	
}