<?php

/**
 * Admin_Model_AffiliatePromotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_AffiliatePromotion extends Admin_Model_Base_AffiliatePromotion
{
	const PROMO_REGEX = '/^(\d+|\d+\.\d+)$/i';
	
	public function getActivePromotions($limit = null){
    	$daoFilter = new Rhema_Dao_Filter();
    	$daoFilter->setModel(__CLASS__) 
    			  ->addCondition('is_active', 1, Rhema_Dao_Filter::OP_EQ) 
    			  ->addOrderBy('title');
		if($limit){
			$daoFilter->setLimit($limit);
		}  
    	return Rhema_Model_Service::createQuery($daoFilter)->execute();
	}

	public static function findPromo($id){
 
		$filter = new Rhema_Dao_Filter(); 
		$filter->setModel(__CLASS__)
			   ->addCondition('id', $id);
		 
		return Rhema_Model_Service::createQuery($filter)->fetchOne(); 
	}
}