<?php

/**
 * Admin_Model_AffiliateFeaturedCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_AffiliateFeaturedCategory extends Admin_Model_Base_AffiliateFeaturedCategory
{
	
	public function getFeaturedCategory($limit = 3){
		$filter = new Rhema_Dao_Filter($limit);
		$filter->setModel(__CLASS__)
			   ->addJoin('AffiliateProductCategory')
			   ->addOrderBy('sort_order')
			   ->addCondition('is_active', 1);
		return Rhema_Model_Service::createQuery($filter)->execute();			
	}
}