<?php

/**
 * Admin_Model_BlogPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_BlogPost extends Admin_Model_Base_BlogPost
{

	public function getBlogPosts($limit = 10, $page = null){
		$model = __CLASS__ ;
		$auth  = Zend_Auth::getInstance();
		
		if($auth->hasIdentity()){
			$user = $auth->getIdentity();
			$roleSequence = $user['Role']['sequence'];
		}else{
			$roleSequence = 1;
		}
		
		$filter = new Rhema_Dao_Filter();
		$filter->setModel($model) 
			   ->addJoin('User', Rhema_Dao_Filter::LEFT_JOIN, array('firstname', 'lastname'))
			   ->addJoin('Role', Rhema_Dao_Filter::LEFT_JOIN, array('title'))
			   ->addJoin('Category', Rhema_Dao_Filter::INNER_JOIN, array('title'))
			   ->addOrderBy('created_at', Rhema_Dao_Filter::ORDER_DESC)
			   ->addCondition('is_active', 1)			   
			   ->addCondition('Role.sequence', $roleSequence, Rhema_Dao_Filter::OP_LTE) ;
			   
		if($limit){
			$filter->setLimit($limit);
		}	  
 
		if($page){
			$paginator = Rhema_Model_Service::getPaginator($filter, $page); 
		}else{
			$paginator = Rhema_Model_Service::createQuery($filter)->execute();
		}
 
		return $paginator;
	}
	
	public static function getItem($slug){
		$model = __CLASS__ ;
		$query = Doctrine_Query::create()
				 ->from("$model m")
				 ->where('m.slug =?', $slug)
				 ->andWhere('m.is_active =?', 1)
				 ->leftJoin('m.PostComments p')
				 ->leftJoin('m.BlogCategory c')
				 ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
		$result = $query->execute();
		return 	count($result) ? $result[0] : array();	
	}
}