<?php

/**
 * Admin_Model_EcomOrder
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_EcomOrder extends Admin_Model_Base_EcomOrder
{

    public static function saveTransaction($orderDetail){
        $model   = __CLASS__ ;
        $object  = new $model;
        $files   = array();
        $root    = Zend_Controller_Front::getInstance()->getRequest()->getServer('DOCUMENT_ROOT');


        $userEmail = $orderDetail['payer_email'];
        $invoice   = $orderDetail['invoice'];
        $trans     = Doctrine_Core::getTable(__CLASS__)->findByInvoice($invoice);
        $basket    = new Ecom_Service_Cart();

        if(count($trans)){
            $basket->clearSession();
            $url        = Zend_Layout::getMvcInstance()->getView()->url(array('slug'=> 'index'), 'site-default-route');
            $redirector = Zend_Controller_Action_HelperBroker::getStaticHelper('redirector');
            $redirector->gotoUrlAndExit($url);

        }else{
            if($userEmail){
                $auth = Zend_Auth::getInstance();
                if($auth->hasIdentity()){
                    $user = $auth->getIdentity();
                    $object->user_id = $user['id'];
                }else{
                    $user            = Doctrine_Core::getTable('Admin_Model_User')->findByEmail($userEmail);
                    $object->user_id = $user ? $user->id : '';
                }
            }
            $object->payer       = $orderDetail['payer_id'];
            $object->txn         = $orderDetail['txn_id'];
            $object->receiver    = $orderDetail['receiver_id'];

            $object->fromArray($orderDetail);
            $object->save();


            foreach($basket as $item){
                $orderData                = new Admin_Model_EcomOrderDetail();
                $orderData->title         = $item->name;
                $orderData->price         = $item->price;
                $orderData->quantity      = $item->qty;
                $orderData->ecom_order_id = $object->id;
                $orderData->image_file    = $item->thumb;
                $orderData->discount      = $item->discountPercent;
                $orderData->code          = $item->code;
                $orderData->ecom_product_id = 0;
                $orderData->is_virtual    = 1;

                if($item->isVirtual){
                    $orderData->image_download  = $root . '/' . PHOTOBOOK_DIR . '/' . $item->downloadPath . '/' . basename($item->thumb);
                    $files[] = $orderData->image_download ;
                }

                $orderData->save();
            }

            if(count($files)){
                $paths       = Rhema_Util::createSiteDirectory('download');
                $zipFilename = $paths[0] . '/' . $object->invoice . '.zip';
                $zipFile     = Rhema_Util_File::createZip($files, $zipFilename);
                $object->download = $zipFilename ;
                $object->save();
            }
        }
    }

    public function createDownload(){

    }

    public function __toString(){
        return $this->invoice;
    }


}