<?php

/**
 * Admin_Model_EcomDeliveryMethod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_EcomDeliveryMethod extends Admin_Model_Base_EcomDeliveryMethod{

	public static function getDeliveryMethods(Rhema_Dao_Filter $filter = null ){
		$model  = __CLASS__;
		$filter = $filter ? $filter : new Rhema_Dao_Filter();
		$filter->setModel(__CLASS__) ;
		
		return Rhema_Model_Service::createQuery($filter)->execute(); 
	}
}