<?php

/**
 * Admin_Model_EcomAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_EcomAttribute extends Admin_Model_Base_EcomAttribute{

	/*public static function getAttributeTemplates($templateId = null, $display_type = 1){
		$output 		= array();
		$templateId 	= $templateId ? $templateId : 
							Admin_Model_EcomDisplayTemplate::getDefaultTemplate($display_type);
		if($templateId){
			Rhema_Util::setSessData('display_template_id_' . $display_type, $templateId);
			
			$arr    		= Admin_Model_EcomTemplateAttribute::getAttributes($templateId);
			$model  		= __CLASS__ ;
			$output 		= array();
			$whereIds       = array();
			
			foreach($arr as $data){
				$id                = $data['ecom_attribute_id'];
				$whereIds[$id ]    = $data; 
			} 
			
			$query  = Doctrine_Query::create()
						->select('m.title,m.is_tab,m.template,m.is_labeled,m.placeholder')
						->from("$model m INDEXBY m.id")
						->whereIn('m.id', array_keys($whereIds))
						->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
	 		$attrs  = $query->execute();		
			
			foreach($attrs as $id => $data){
				if(isset($whereIds[$id])){
					$seq   = $whereIds[$id]['sequence'];
					$sec   = $data['is_tab'] ? 'tab' : 'attr';
					$output[$sec][$seq] = $data;
				}
			}
	 			
			ksort($output);
		}
		return $output; 	
			
	}*/
	 
}