<?php

/**
 * Admin_Model_Featured
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_Featured extends Admin_Model_Base_Featured
{
	public static function getFeaturedItems(){
		$model = __CLASS__;
		$query = Doctrine_Query::create()
					->select('m.*,g.module,g.controller,g.action')
					->from("$model m")
					->where('m.is_active =?', 1)
					->orderBy('m.sequence')
					->leftJoin('m.Menu g')
					//->useResultCache(true)
					->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
		return $query->execute();
	}
}