<?php

/**
 * Admin_Model_Menu
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Admin_Model_Menu extends Admin_Model_Base_Menu{

	/*public function getMainMenu($options){
		return $this->frontEndMenus($options);
	}*/

	public static function getPageMenu($page_id, $mode =Doctrine_Core::HYDRATE_ARRAY, $limit = 1){
		$model  = __CLASS__;
		$query = Doctrine_Query::create()
					->from("$model t")
					->where('t.page_id =?', $page_id) 
					->limit($limit);
		if($mode){
			$query->setHydrationMode($mode);
		}

		return $query->execute();
	}
	
 	public function getMenuReferencingPage($pageId){
 		$filter = new Rhema_Dao_Filter();
 		$filter->setModel(__CLASS__)
 			   ->addFields(array('title', 'label','m_action', 'image_file'))
 			   //->setDebug()
 			   ->addCondition('level', 0, Rhema_Dao_Filter::OP_GT)
 			   ->addCondition('page_id', $pageId);
 		$result = Rhema_Model_Service::createQuery($filter)->execute();
 		//pd($result);
 		return $result;
 	}
}