<?php

/**
 * Admin_Model_SlideCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_SlideCategory extends Admin_Model_Base_SlideCategory
{
	public function getSlideData($slideId = null, $item = array()){		 
		$field    = 'AffiliateProductCategory'; 
		$filter = new Rhema_Dao_Filter();
		$filter->setModel(__CLASS__) 
			   ->addJoin($field, Rhema_Dao_Filter::INNER_JOIN, array('logo', 'title', 'image_file', 'slug')) 
			   ->addCondition('slide_id', $item['id']) ; 
		$return = Rhema_Model_Service::createQuery($filter)->execute();	
		if($return){ 
			foreach($return as $list){ 
				$item[$field][] = $list[$field]; 
			}				
		}else{
			$item[$field] = array();
		}
		   
		return $item;
	}
}