<?php

/**
 * Admin_Model_Slide
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Slide extends Admin_Model_Base_Slide
{
	public function getActiveSlides(){
		$filter = new Rhema_Dao_Filter();
		$filter->setModel(__CLASS__) 
			   ->addCondition('is_active', 1)  
			   ->addOrderBy('sort_order');	
		return Rhema_Model_Service::createQuery($filter)->execute();
	}
}