<?php

/**
 * Admin_Model_SlideRetailer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_SlideRetailer extends Admin_Model_Base_SlideRetailer
{
	public function getSlideData($slideId = null, $item = array()){ 
		$filter = new Rhema_Dao_Filter();
		$filter->setModel(__CLASS__) 
			   ->addJoin('AffiliateRetailer', Rhema_Dao_Filter::INNER_JOIN, array('logo', 'title', 'image_file', 'slug')) 
			   ->addCondition('slide_id', $item['id'])
			   ->addCondition('AffiliateRetailer.is_active', 1) ; 
		$return = Rhema_Model_Service::createQuery($filter)->execute();	
		if($return){ 
			foreach($return as $list){ 
				$item['AffiliateRetailer'][] = $list['AffiliateRetailer']; 
			}				
		}else{
			$item['AffiliateRetailer'] = array();
		}
		 
		return $item;
	}
}