<?php

/**
 * Admin_Model_Translation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Translation extends Admin_Model_Base_Translation
{
	public static function getLocaleTranslations($locale, $type){
		$fallback  = 'en_GB';
		$results   = array();
		
	    $daoFilter = new Rhema_Dao_Filter(); 
    	$daoFilter->addFields(array('trans_key', $fallback, $locale))  
    			  ->addCondition('file_type', $type)
    			  ->setModel(__CLASS__); 
    	
 	  	$rows = Rhema_Model_Service::createQuery($daoFilter)->execute(); 	
	        
 	  	foreach((array)$rows as $row) {
            $transkey = $row['trans_key']; 
            if($transkey){
                $val = (isset($row[$locale]) and $row[$locale]) ? $row[$locale] : (isset($row[$fallback]) ? $row[$fallback] : '');
                $results[$transkey][$locale] = $val ; 
            }
        }
        
        return $results;
	}
	
	public function getTranslationKey($field, $value, $type = 'content'){
	    $daoFilter = new Rhema_Dao_Filter(); 
    	$daoFilter->addFields(array('trans_key', $field))  
    			  ->addCondition('file_type', $type)
    			  ->addCondition($field, $value)
    			  ->setModel(__CLASS__); 	
    	$res = 	Rhema_Model_Service::createQuery($daoFilter)->fetchOne();
    	return $res ? $res['trans_key'] : false;
	}
}