<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AddressBook', 'admin');

/**
 * Admin_Model_Base_AddressBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $line1
 * @property string $line2
 * @property string $line3
 * @property string $city
 * @property string $state
 * @property string $post_code
 * @property string $region
 * @property string $country
 * @property Doctrine_Collection $User
 * @property Admin_Model_AdminSubsite $AdminSubsite
 * @property Doctrine_Collection $UserAddresses
 * @property Admin_Model_Event $Event
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AddressBook extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('address_book');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 45, array(
             'type' => 'string',
             'default' => 'home',
             'length' => '45',
             ));
        $this->hasColumn('line1', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('line2', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('line3', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('city', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('state', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('post_code', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('region', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('country', 'string', 10, array(
             'type' => 'string',
             'country' => true,
             'length' => '10',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_User as User', array(
             'refClass' => 'Admin_Model_UserAddress',
             'local' => 'address_book_id',
             'foreign' => 'user_id'));

        $this->hasOne('Admin_Model_AdminSubsite as AdminSubsite', array(
             'local' => 'id',
             'foreign' => 'address_book_id'));

        $this->hasMany('Admin_Model_UserAddress as UserAddresses', array(
             'local' => 'id',
             'foreign' => 'address_book_id'));

        $this->hasOne('Admin_Model_Event as Event', array(
             'local' => 'id',
             'foreign' => 'address_book_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $geographical0 = new Doctrine_Template_Geographical();
        $this->actAs($timestampable0);
        $this->actAs($geographical0);
    }
}