<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AdminSubsiteLicence', 'admin');

/**
 * Admin_Model_Base_AdminSubsiteLicence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $admin_licence_id
 * @property integer $admin_subsite_id
 * @property integer $is_active
 * @property Admin_Model_AdminLicence $AdminLicence
 * @property Admin_Model_AdminSubsite $AdminSubsite
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AdminSubsiteLicence extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_subsite_licence');
        $this->hasColumn('admin_licence_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('admin_subsite_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AdminLicence as AdminLicence', array(
             'local' => 'admin_licence_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AdminSubsite as AdminSubsite', array(
             'local' => 'admin_subsite_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}