<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AdminState', 'admin');

/**
 * Admin_Model_Base_AdminState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $code
 * @property string $country
 * @property integer $ecom_tax_id
 * @property Admin_Model_EcomTax $EcomTax
 * @property Admin_Model_AdminCounty $AdminCounty
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AdminState extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_state');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('code', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('country', 'string', 100, array(
             'type' => 'string',
             'country' => true,
             'length' => '100',
             ));
        $this->hasColumn('ecom_tax_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_EcomTax as EcomTax', array(
             'local' => 'ecom_tax_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AdminCounty as AdminCounty', array(
             'local' => 'id',
             'foreign' => 'admin_state_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}