<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AdminCurrency', 'admin');

/**
 * Admin_Model_Base_AdminCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $code
 * @property decimal $rate
 * @property string $symbol
 * @property integer $position
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AdminCurrency extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_currency');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('code', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('rate', 'decimal', 18, array(
             'type' => 'decimal',
             'length' => '18',
             ));
        $this->hasColumn('symbol', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
        $this->hasColumn('position', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}