<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AdminLicence', 'admin');

/**
 * Admin_Model_Base_AdminLicence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $licence_key
 * @property float $price
 * @property Admin_Model_AdminElement $AdminElement
 * @property Doctrine_Collection $SubsiteLicence
 * @property Admin_Model_AdminModule $AdminModule
 * @property Doctrine_Collection $LicencedModules
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AdminLicence extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_licence');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('licence_key', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'default' => 'FREE',
             'length' => '45',
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AdminElement as AdminElement', array(
             'local' => 'id',
             'foreign' => 'admin_licence_id'));

        $this->hasMany('Admin_Model_AdminSubsiteLicence as SubsiteLicence', array(
             'local' => 'id',
             'foreign' => 'admin_licence_id'));

        $this->hasOne('Admin_Model_AdminModule as AdminModule', array(
             'local' => 'id',
             'foreign' => 'admin_licence_id'));

        $this->hasMany('Admin_Model_AdminSubsite as LicencedModules', array(
             'refClass' => 'Admin_Model_AdminSubsiteLicence',
             'local' => 'admin_licence_id',
             'foreign' => 'admin_subsite_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}