<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AdminContentType', 'admin');

/**
 * Admin_Model_Base_AdminContentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $code
 * @property integer $admin_table_id
 * @property string $thumb
 * @property string $color
 * @property integer $is_table
 * @property integer $sequence
 * @property string $note
 * @property Admin_Model_AdminTable $AdminTable
 * @property Doctrine_Collection $ContentType
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AdminContentType extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_content_type');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('code', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'notblank' => true,
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('admin_table_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('thumb', 'string', 145, array(
             'type' => 'string',
             'length' => '145',
             ));
        $this->hasColumn('color', 'string', 7, array(
             'type' => 'string',
             'htmlcolor' => 'true;',
             'length' => '7',
             ));
        $this->hasColumn('is_table', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('sequence', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AdminTable as AdminTable', array(
             'local' => 'admin_table_id',
             'foreign' => 'id'));

        $this->hasMany('Admin_Model_PageLayout as ContentType', array(
             'local' => 'id',
             'foreign' => 'admin_content_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}