<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AdminTable', 'admin');

/**
 * Admin_Model_Base_AdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $name
 * @property integer $is_admin
 * @property integer $is_hidden
 * @property string $note
 * @property integer $admin_category_id
 * @property integer $admin_database_id
 * @property Admin_Model_AdminCategory $AdminCategory
 * @property Admin_Model_AdminDatabase $AdminDatabase
 * @property Admin_Model_AdminContentType $AdminContentType
 * @property Doctrine_Collection $SourceTable
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AdminTable extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_table');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('is_admin', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('is_hidden', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('note', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('admin_category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => '4',
             ));
        $this->hasColumn('admin_database_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AdminCategory as AdminCategory', array(
             'local' => 'admin_category_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AdminDatabase as AdminDatabase', array(
             'local' => 'admin_database_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AdminContentType as AdminContentType', array(
             'local' => 'id',
             'foreign' => 'admin_table_id'));

        $this->hasMany('Admin_Model_PageLayout as SourceTable', array(
             'local' => 'id',
             'foreign' => 'admin_table_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}