<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AdminMenu', 'admin');

/**
 * Admin_Model_Base_AdminMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $label
 * @property string $m_module
 * @property string $m_controller
 * @property integer $sequence
 * @property string $m_action
 * @property string $m_route
 * @property string $image_file
 * @property integer $is_label
 * @property integer $is_visible
 * @property Admin_Model_AdminModule $AdminModule
 * @property Admin_Model_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AdminMenu extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_menu');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('m_module', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'storefront',
             'length' => '45',
             ));
        $this->hasColumn('m_controller', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'index',
             'length' => '45',
             ));
        $this->hasColumn('sequence', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '4',
             ));
        $this->hasColumn('m_action', 'string', 45, array(
             'type' => 'string',
             'default' => 'index',
             'length' => '45',
             ));
        $this->hasColumn('m_route', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('image_file', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('is_label', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('is_visible', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AdminModule as AdminModule', array(
             'local' => 'id',
             'foreign' => 'admin_menu_id'));

        $this->hasOne('Admin_Model_User as User', array(
             'local' => 'id',
             'foreign' => 'admin_menu_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
    }
}