<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AffiliateProductCategory', 'admin');

/**
 * Admin_Model_Base_AffiliateProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property integer $categoryid
 * @property string $category_name
 * @property string $category_path
 * @property string $merchant_category
 * @property integer $sequence
 * @property string $params
 * @property integer $affiliate_network_id
 * @property integer $is_adult
 * @property Admin_Model_AffiliateNetwork $AffiliateNetwork
 * @property Admin_Model_AffiliateFeaturedCategory $AffiliateFeaturedCategory
 * @property Admin_Model_AffiliateProduct $AffiliateProduct
 * @property Admin_Model_Slide $Slide
 * @property Admin_Model_SlideCategory $SlideCategory
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AffiliateProductCategory extends Admin_Model_AdminMenu
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('affiliate_product_category');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('keywords', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('categoryid', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('category_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('category_path', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('merchant_category', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('sequence', 'integer', 3, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '3',
             ));
        $this->hasColumn('params', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('affiliate_network_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('is_adult', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));


        $this->index('title_index', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->index('adult_index', array(
             'fields' => 
             array(
              0 => 'is_adult',
             ),
             ));
        $this->index('deleted_index', array(
             'fields' => 
             array(
              0 => 'deleted_at',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AffiliateNetwork as AffiliateNetwork', array(
             'local' => 'affiliate_network_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AffiliateFeaturedCategory as AffiliateFeaturedCategory', array(
             'local' => 'id',
             'foreign' => 'affiliate_product_category_id'));

        $this->hasOne('Admin_Model_AffiliateProduct as AffiliateProduct', array(
             'local' => 'id',
             'foreign' => 'affiliate_product_category_id'));

        $this->hasOne('Admin_Model_Slide as Slide', array(
             'local' => 'id',
             'foreign' => 'affiliate_product_category_id'));

        $this->hasOne('Admin_Model_SlideCategory as SlideCategory', array(
             'local' => 'id',
             'foreign' => 'affiliate_product_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
              1 => 'admin_subsite_id',
             ),
             'canUpdate' => true,
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($softdelete0);
        $this->actAs($nestedset0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($searchable0);
    }
}