<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AffiliateRetailer', 'admin');

/**
 * Admin_Model_Base_AffiliateRetailer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $strapline
 * @property string $keywords
 * @property string $tags
 * @property string $feed_url
 * @property string $logo
 * @property string $image_file
 * @property string $deeplink
 * @property string $category
 * @property integer $affiliate_retailer_type_id
 * @property integer $programid
 * @property string $program_name
 * @property integer $is_active
 * @property integer $is_adult
 * @property integer $affiliate_retailer_id
 * @property integer $affiliate_network_id
 * @property Admin_Model_AffiliateRetailer $AffiliateRetailer
 * @property Admin_Model_AffiliateNetwork $AffiliateNetwork
 * @property Admin_Model_AffiliateRetailerType $AffiliateRetailerType
 * @property Admin_Model_AffiliateBanner $AffiliateBanner
 * @property Admin_Model_AffiliateProduct $AffiliateProduct
 * @property Admin_Model_SlideRetailer $SlideRetailer
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AffiliateRetailer extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('affiliate_retailer');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('strapline', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('keywords', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tags', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('feed_url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('image_file', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('deeplink', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('affiliate_retailer_type_id', 'integer', 8, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '8',
             ));
        $this->hasColumn('programid', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('program_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('is_adult', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('affiliate_retailer_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('affiliate_network_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '8',
             ));


        $this->index('deleted_index', array(
             'fields' => 
             array(
              0 => 'deleted_at',
             ),
             ));
        $this->index('title_index', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->index('is_active_index', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->index('adult_index', array(
             'fields' => 
             array(
              0 => 'is_adult',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AffiliateRetailer as AffiliateRetailer', array(
             'local' => 'affiliate_retailer_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AffiliateNetwork as AffiliateNetwork', array(
             'local' => 'affiliate_network_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AffiliateRetailerType as AffiliateRetailerType', array(
             'local' => 'affiliate_retailer_type_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AffiliateBanner as AffiliateBanner', array(
             'local' => 'id',
             'foreign' => 'affiliate_retailer_id'));

        $this->hasOne('Admin_Model_AffiliateProduct as AffiliateProduct', array(
             'local' => 'id',
             'foreign' => 'affiliate_retailer_id'));

        $this->hasOne('Admin_Model_SlideRetailer as SlideRetailer', array(
             'local' => 'id',
             'foreign' => 'affiliate_retailer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'title',
              1 => 'admin_subsite_id',
             ),
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($softdelete0);
        $this->actAs($sluggable0);
        $this->actAs($searchable0);
    }
}