<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_AffiliateProductBrand', 'admin');

/**
 * Admin_Model_Base_AffiliateProductBrand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property integer $is_active
 * @property integer $sort_order
 * @property string $brand_type
 * @property Admin_Model_AffiliateBanner $AffiliateBanner
 * @property Doctrine_Collection $AffiliateProduct
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_AffiliateProductBrand extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('affiliate_product_brand');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('keywords', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('sort_order', 'integer', 8, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '8',
             ));
        $this->hasColumn('brand_type', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));


        $this->index('deleted_index', array(
             'fields' => 
             array(
              0 => 'deleted_at',
             ),
             ));
        $this->index('title_index', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->index('is_active_index', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AffiliateBanner as AffiliateBanner', array(
             'local' => 'id',
             'foreign' => 'affiliate_product_brand_id'));

        $this->hasMany('Admin_Model_AffiliateProduct as AffiliateProduct', array(
             'local' => 'id',
             'foreign' => 'affiliate_product_brand_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'title',
              1 => 'admin_subsite_id',
             ),
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($softdelete0);
        $this->actAs($sluggable0);
        $this->actAs($searchable0);
    }
}