<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_BlogPost', 'admin');

/**
 * Admin_Model_Base_BlogPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keyword
 * @property string $excerpt
 * @property integer $is_active
 * @property integer $blog_category_id
 * @property string $content
 * @property integer $role_id
 * @property string $image_file
 * @property integer $author
 * @property Admin_Model_BlogCategory $BlogCategory
 * @property Admin_Model_User $User
 * @property Admin_Model_Role $Role
 * @property Doctrine_Collection $PostComment
 * @property Doctrine_Collection $PostComments
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_BlogPost extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_post');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('keyword', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('excerpt', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('blog_category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '4',
             ));
        $this->hasColumn('image_file', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('user_id as author', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_BlogCategory as BlogCategory', array(
             'local' => 'blog_category_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasMany('Admin_Model_BlogComment as PostComment', array(
             'refClass' => 'Admin_Model_BlogPostComment',
             'local' => 'blog_post_id',
             'foreign' => 'blog_comment_id'));

        $this->hasMany('Admin_Model_BlogPostComment as PostComments', array(
             'local' => 'id',
             'foreign' => 'blog_post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $blameable0 = new Doctrine_Template_Blameable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($blameable0);
        $this->actAs($sluggable0);
    }
}