<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_BlogPostComment', 'admin');

/**
 * Admin_Model_Base_BlogPostComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $blog_post_id
 * @property integer $blog_comment_id
 * @property Admin_Model_BlogPost $BlogPost
 * @property Admin_Model_BlogComment $BlogComment
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_BlogPostComment extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_post_comment');
        $this->hasColumn('blog_post_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('blog_comment_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_BlogPost as BlogPost', array(
             'local' => 'blog_post_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_BlogComment as BlogComment', array(
             'local' => 'blog_comment_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
    }
}