<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_EcomTax', 'admin');

/**
 * Admin_Model_Base_EcomTax
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property decimal $rate
 * @property Admin_Model_AdminCounty $AdminCounty
 * @property Admin_Model_AdminState $AdminState
 * @property Admin_Model_EcomCategory $EcomCategory
 * @property Admin_Model_EcomProduct $EcomProduct
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_EcomTax extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('ecom_tax');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('rate', 'decimal', 18, array(
             'type' => 'decimal',
             'default' => 0,
             'length' => '18',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AdminCounty as AdminCounty', array(
             'local' => 'id',
             'foreign' => 'ecom_tax_id'));

        $this->hasOne('Admin_Model_AdminState as AdminState', array(
             'local' => 'id',
             'foreign' => 'ecom_tax_id'));

        $this->hasOne('Admin_Model_EcomCategory as EcomCategory', array(
             'local' => 'id',
             'foreign' => 'ecom_tax_id'));

        $this->hasOne('Admin_Model_EcomProduct as EcomProduct', array(
             'local' => 'id',
             'foreign' => 'ecom_tax_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}