<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_EcomCategory', 'admin');

/**
 * Admin_Model_Base_EcomCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $code
 * @property string $description
 * @property string $image_file
 * @property integer $ecom_tax_id
 * @property Admin_Model_EcomTax $EcomTax
 * @property Admin_Model_EcomNavigationMenu $EcomNavigationMenu
 * @property Doctrine_Collection $Products
 * @property Doctrine_Collection $ProductCategory
 * @property Admin_Model_EcomPersLayout $EcomPersLayout
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_EcomCategory extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('ecom_category');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('code', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('image_file', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('ecom_tax_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_EcomTax as EcomTax', array(
             'local' => 'ecom_tax_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_EcomNavigationMenu as EcomNavigationMenu', array(
             'local' => 'id',
             'foreign' => 'ecom_category_id'));

        $this->hasMany('Admin_Model_EcomProduct as Products', array(
             'refClass' => 'Admin_Model_EcomProductCategory',
             'local' => 'ecom_category_id',
             'foreign' => 'ecom_product_id'));

        $this->hasMany('Admin_Model_EcomProductCategory as ProductCategory', array(
             'local' => 'id',
             'foreign' => 'ecom_category_id'));

        $this->hasOne('Admin_Model_EcomPersLayout as EcomPersLayout', array(
             'local' => 'id',
             'foreign' => 'ecom_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 'title',
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}