<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_EcomAttribute', 'admin');

/**
 * Admin_Model_Base_EcomAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $label
 * @property string $template
 * @property string $placeholder
 * @property integer $is_labeled
 * @property integer $is_product
 * @property integer $is_tab
 * @property Doctrine_Collection $DisplayTemplate
 * @property Doctrine_Collection $TemplateAttributes
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_EcomAttribute extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('ecom_attribute');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('label', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('template', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('placeholder', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('is_labeled', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('is_product', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('is_tab', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_EcomDisplayTemplate as DisplayTemplate', array(
             'refClass' => 'Admin_Model_EcomTemplateAttribute',
             'local' => 'ecom_attribute_id',
             'foreign' => 'ecom_display_template_id'));

        $this->hasMany('Admin_Model_EcomTemplateAttribute as TemplateAttributes', array(
             'local' => 'id',
             'foreign' => 'ecom_attribute_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}