<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_EcomDisplayTemplate', 'admin');

/**
 * Admin_Model_Base_EcomDisplayTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property integer $is_default
 * @property integer $ecom_display_type_id
 * @property string $note
 * @property Admin_Model_EcomDisplayType $EcomDisplayType
 * @property Doctrine_Collection $EcomAttribute
 * @property Doctrine_Collection $TemplateAttributes
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_EcomDisplayTemplate extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('ecom_display_template');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_default', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('ecom_display_type_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_EcomDisplayType as EcomDisplayType', array(
             'local' => 'ecom_display_type_id',
             'foreign' => 'id'));

        $this->hasMany('Admin_Model_EcomAttribute as EcomAttribute', array(
             'refClass' => 'Admin_Model_EcomTemplateAttribute',
             'local' => 'ecom_display_template_id',
             'foreign' => 'ecom_attribute_id'));

        $this->hasMany('Admin_Model_EcomTemplateAttribute as TemplateAttributes', array(
             'local' => 'id',
             'foreign' => 'ecom_display_template_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
    }
}