<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Event', 'admin');

/**
 * Admin_Model_Base_Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keyword
 * @property string $location
 * @property string $content
 * @property timestamp $start_at
 * @property timestamp $end_at
 * @property integer $event_type_id
 * @property integer $address_book_id
 * @property integer $user_id
 * @property integer $is_active
 * @property integer $is_allday
 * @property integer $is_sale
 * @property string $color
 * @property string $recurring_rule
 * @property string $image_file
 * @property Admin_Model_AddressBook $AddressBook
 * @property Admin_Model_EventType $EventType
 * @property Admin_Model_User $User
 * @property Admin_Model_Portfolio $Portfolio
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Event extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('keyword', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('location', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '500',
             ));
        $this->hasColumn('content', 'string', 2048, array(
             'type' => 'string',
             'length' => '2048',
             ));
        $this->hasColumn('start_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('end_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('event_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('address_book_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '4',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('is_allday', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('is_sale', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('color', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('recurring_rule', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('image_file', 'string', 145, array(
             'type' => 'string',
             'length' => '145',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AddressBook as AddressBook', array(
             'local' => 'address_book_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_EventType as EventType', array(
             'local' => 'event_type_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Portfolio as Portfolio', array(
             'local' => 'id',
             'foreign' => 'event_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
    }
}