<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Featured', 'admin');

/**
 * Admin_Model_Base_Featured
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $menu_id
 * @property string $label
 * @property string $caption
 * @property string $description
 * @property string $image_file
 * @property string $thumb
 * @property string $note
 * @property string $information
 * @property string $css
 * @property integer $is_active
 * @property integer $sequence
 * @property Admin_Model_Menu $Menu
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Featured extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('featured');
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('menu_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('label', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('caption', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('image_file', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('thumb', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('information', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('css', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('sequence', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Menu as Menu', array(
             'local' => 'menu_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $blameable0 = new Doctrine_Template_Blameable();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($softdelete0);
        $this->actAs($blameable0);
    }
}