<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_HelpBoilerPlate', 'admin');

/**
 * Admin_Model_Base_HelpBoilerPlate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $content
 * @property integer $is_active
 * @property Doctrine_Collection $Plates
 * @property Doctrine_Collection $Templates
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_HelpBoilerPlate extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('help_boiler_plate');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_HelpTemplateBoilerPlate as Plates', array(
             'local' => 'id',
             'foreign' => 'help_boiler_plate_id'));

        $this->hasMany('Admin_Model_HelpTemplate as Templates', array(
             'refClass' => 'Admin_Model_HelpTemplateBoilerPlate',
             'local' => 'help_boiler_plate_id',
             'foreign' => 'help_template_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}