<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_HelpDocument', 'admin');

/**
 * Admin_Model_Base_HelpDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keyword
 * @property string $content
 * @property string $answer
 * @property string $related_item
 * @property string $question
 * @property integer $module
 * @property integer $help_type_id
 * @property integer $help_category_id
 * @property integer $role_id
 * @property integer $admin_group_id
 * @property Admin_Model_HelpCategory $HelpCategory
 * @property Admin_Model_HelpType $HelpType
 * @property Admin_Model_Role $Role
 * @property Admin_Model_AdminGroup $AdminGroup
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_HelpDocument extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('help_document');
        $this->hasColumn('title', 'string', 145, array(
             'type' => 'string',
             'length' => '145',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('keyword', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('answer', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('related_item', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('question', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('module', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('help_type_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('help_category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('admin_group_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_HelpCategory as HelpCategory', array(
             'local' => 'help_category_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_HelpType as HelpType', array(
             'local' => 'help_type_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AdminGroup as AdminGroup', array(
             'local' => 'admin_group_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'content',
              1 => 'title',
              2 => 'description',
              3 => 'keyword',
             ),
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($searchable0);
        $this->actAs($sluggable0);
        $this->actAs($softdelete0);
    }
}