<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Inquiry', 'admin');

/**
 * Admin_Model_Base_Inquiry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user_id
 * @property string $salutation_id
 * @property integer $subject_id
 * @property string $url
 * @property string $messsage
 * @property integer $is_resolved
 * @property string $ip_address
 * @property Admin_Model_User $User
 * @property Admin_Model_Subject $Subject
 * @property Admin_Model_Salutation $Salutation
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Inquiry extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('inquiry');
        $this->hasColumn('user_id', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('salutation_id', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('subject_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('url', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('messsage', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('is_resolved', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('ip_address', 'string', 15, array(
             'type' => 'string',
             'ip' => true,
             'length' => '15',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Subject as Subject', array(
             'local' => 'subject_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Salutation as Salutation', array(
             'local' => 'salutation_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $blameable0 = new Doctrine_Template_Blameable();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($softdelete0);
        $this->actAs($blameable0);
    }
}