<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Menu', 'admin');

/**
 * Admin_Model_Base_Menu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sequence
 * @property integer $page_id
 * @property string $params
 * @property Admin_Model_Page $Page
 * @property Admin_Model_Featured $Featured
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Menu extends Admin_Model_AdminMenu
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('menu');
        $this->hasColumn('sequence', 'integer', 3, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '3',
             ));
        $this->hasColumn('page_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('params', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('menuindex', array(
             'fields' => 
             array(
              0 => 'page_id',
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Page as Page', array(
             'local' => 'page_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Featured as Featured', array(
             'local' => 'id',
             'foreign' => 'menu_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'label',
             ),
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'label',
              1 => 'admin_subsite_id',
             ),
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($softdelete0);
        $this->actAs($nestedset0);
        $this->actAs($rhema_model_template_subsite0);
    }
}