<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Page', 'admin');

/**
 * Admin_Model_Base_Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $meta_title
 * @property string $description
 * @property integer $category_id
 * @property integer $is_active
 * @property string $keyword
 * @property timestamp $start_at
 * @property timestamp $end_at
 * @property integer $is_hidden
 * @property integer $is_cached
 * @property integer $is_secure
 * @property integer $template_id
 * @property integer $page_header_id
 * @property integer $page_footer_id
 * @property string $note
 * @property Admin_Model_Category $Category
 * @property Admin_Model_PageHeader $PageHeader
 * @property Admin_Model_Template $Template
 * @property Admin_Model_PageFooter $PageFooter
 * @property Doctrine_Collection $PageMenu
 * @property Doctrine_Collection $PageLayout
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Page extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('meta_title', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('keyword', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('start_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('end_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('is_hidden', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('is_cached', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('is_secure', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('template_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('page_header_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('page_footer_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Category as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_PageHeader as PageHeader', array(
             'local' => 'page_header_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Template as Template', array(
             'local' => 'template_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_PageFooter as PageFooter', array(
             'local' => 'page_footer_id',
             'foreign' => 'id'));

        $this->hasMany('Admin_Model_Menu as PageMenu', array(
             'local' => 'id',
             'foreign' => 'page_id'));

        $this->hasMany('Admin_Model_PageLayout as PageLayout', array(
             'local' => 'id',
             'foreign' => 'page_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $blameable0 = new Doctrine_Template_Blameable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'uniqueBy' => 
             array(
              0 => 'title',
              1 => 'admin_subsite_id',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($blameable0);
        $this->actAs($softdelete0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($sluggable0);
    }
}