<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Portfolio', 'admin');

/**
 * Admin_Model_Base_Portfolio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keyword
 * @property integer $page_count
 * @property integer $photo_count
 * @property integer $role_id
 * @property string $note
 * @property integer $event_id
 * @property integer $is_active
 * @property integer $is_feature
 * @property integer $is_complete
 * @property string $image_file
 * @property string $album_dir
 * @property string $url
 * @property Admin_Model_Event $Event
 * @property Admin_Model_Role $Role
 * @property Doctrine_Collection $PortfolioComment
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Portfolio extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('portfolio');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('keyword', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('page_count', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('photo_count', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('note', 'string', 2048, array(
             'type' => 'string',
             'length' => '2048',
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('is_feature', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('is_complete', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('image_file', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('album_dir', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('url', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Event as Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasMany('Admin_Model_PortfolioComment as PortfolioComment', array(
             'local' => 'id',
             'foreign' => 'portfolio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'title',
              1 => 'admin_subsite_id',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($sluggable0);
    }
}