<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_PortfolioComment', 'admin');

/**
 * Admin_Model_Base_PortfolioComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $comment
 * @property integer $portfolio_id
 * @property integer $author
 * @property integer $is_active
 * @property decimal $rating
 * @property string $ip_address
 * @property Admin_Model_User $User
 * @property Admin_Model_Portfolio $Portfolio
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_PortfolioComment extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('portfolio_comment');
        $this->hasColumn('comment', 'string', 2048, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2048',
             ));
        $this->hasColumn('portfolio_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id as author', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('rating', 'decimal', 4, array(
             'type' => 'decimal',
             'length' => '4',
             ));
        $this->hasColumn('ip_address', 'string', 15, array(
             'type' => 'string',
             'ip' => true,
             'length' => '15',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_Portfolio as Portfolio', array(
             'local' => 'portfolio_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
    }
}