<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Slide', 'admin');

/**
 * Admin_Model_Base_Slide
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $strapline
 * @property integer $sort_order
 * @property integer $is_active
 * @property integer $is_category
 * @property string $image_file
 * @property string $link
 * @property string $link_text
 * @property string $font_color
 * @property integer $affiliate_product_category_id
 * @property integer $total
 * @property Admin_Model_AffiliateProductCategory $AffiliateProductCategory
 * @property Admin_Model_SlideRetailer $SlideRetailer
 * @property Admin_Model_SlideCategory $SlideCategory
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Slide extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('slide');
        $this->hasColumn('title', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('strapline', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('sort_order', 'integer', 2, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '2',
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('is_category', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('image_file', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('link', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('link_text', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('font_color', 'string', 10, array(
             'type' => 'string',
             'default' => 444444,
             'length' => '10',
             ));
        $this->hasColumn('affiliate_product_category_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '2',
             ));
        $this->hasColumn('total', 'integer', 2, array(
             'type' => 'integer',
             'default' => 12,
             'length' => '2',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_AffiliateProductCategory as AffiliateProductCategory', array(
             'local' => 'affiliate_product_category_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_SlideRetailer as SlideRetailer', array(
             'local' => 'id',
             'foreign' => 'slide_id'));

        $this->hasOne('Admin_Model_SlideCategory as SlideCategory', array(
             'local' => 'id',
             'foreign' => 'slide_id'));
    }
}