<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Template', 'admin');

/**
 * Admin_Model_Base_Template
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property integer $is_header
 * @property integer $is_footer
 * @property string $image_file
 * @property string $thumb
 * @property integer $category_id
 * @property Doctrine_Collection $AdminSection
 * @property Admin_Model_Category $Category
 * @property Admin_Model_AdminSubsite $AdminSubsite
 * @property Admin_Model_PageFooter $PageFooter
 * @property Admin_Model_PageHeader $PageHeader
 * @property Admin_Model_Page $Page
 * @property Doctrine_Collection $TemplateSections
 * @property Doctrine_Collection $Templates
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Template extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('template');
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('description', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('is_header', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('is_footer', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('image_file', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('thumb', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_AdminSection as AdminSection', array(
             'refClass' => 'Admin_Model_TemplateSection',
             'local' => 'template_id',
             'foreign' => 'admin_section_id'));

        $this->hasOne('Admin_Model_Category as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Admin_Model_AdminSubsite as AdminSubsite', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $this->hasOne('Admin_Model_PageFooter as PageFooter', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $this->hasOne('Admin_Model_PageHeader as PageHeader', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $this->hasOne('Admin_Model_Page as Page', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $this->hasMany('Admin_Model_TemplateSection as TemplateSections', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $this->hasMany('Admin_Model_PageLayout as Templates', array(
             'local' => 'id',
             'foreign' => 'template_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
    }
}