<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin_Model_Translation', 'admin');

/**
 * Admin_Model_Base_Translation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $trans_key
 * @property enum $file_type
 * @property string $en_GB
 * @property string $en_US
 * @property string $fr_FR
 * @property string $de_DE
 * @property string $es_ES
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webdesign.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Translation extends Rhema_Model_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('translation');
        $this->hasColumn('trans_key', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('file_type', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 'route',
              1 => 'content',
             ),
             ));
        $this->hasColumn('en_GB', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('en_US', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('fr_FR', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('de_DE', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('es_ES', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $rhema_model_template_subsite0 = new Rhema_Model_Template_Subsite();
        $blameable0 = new Doctrine_Template_Blameable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'trans_key',
              1 => 'file_type',
             ),
             'canUpdate' => true,
             'uniqueBy' => 
             array(
              0 => 'trans_key',
              1 => 'file_type',
              2 => 'admin_subsite_id',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($rhema_model_template_subsite0);
        $this->actAs($blameable0);
        $this->actAs($sluggable0);
    }
}