<?php /* This file encoded by Raizlabs PHP Obfuscator http://www.raizlabs.com/software */ ?>
<?php

/**
 * Help_Model_TemplateBoilerPlate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage RhemaSys
 * @author     Pele Odiase <info@rhema-webesign.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Help_Model_TemplateBoilerPlate extends Help_Model_Base_TemplateBoilerPlate{
 
	public static function getBoilerPlates($template_id, $mode = Doctrine_Core::HYDRATE_ARRAY){
			$table = __CLASS__ ;
			$query = Doctrine_Query::create()
					->select('m.title, m.description, t.*')
					->from("$table t INDEXBY t.boiler_plate_id")
					->leftJoin('t.BoilerPlate m')
					->where('t.template_id =? ', $template_id)
					->orderBy('m.title');
			if($mode){
				$query->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);
			}

			return $query->execute();		
	}
	
	public static function getAllPlates($template_id, $mode = Doctrine_Core::HYDRATE_ARRAY){
			$table = __CLASS__ ;
			$query = Doctrine_Query::create()
					->from("$table t")
					->where('t.template_id =? ', $template_id)
					->andWhere('t.deleted_at IS NOT NULL OR t.deleted_at IS NULL');	
			if($mode){
				$query->setHydrationMode($mode);
			}	
			
			return 	$query->execute();
	}
}