<?php

class Cms_IndexController extends Zend_Controller_Action{

	public function init(){

		/* Initialize action controller here */
		parent::init();

	}

	public function indexAction(){
		 

		//$this->importComments();
		//$this->importFolio();
	}

	public function logAction(){
		$options = Rhema_SiteConfig::getConfig('settings');
		$logDir  = $options['log_dir'];
		if(!file_exists($logDir)){
			mkdir($logDir, 0777, true);
		}
		 
		$this->view->logDir  = realpath(rtrim($logDir, DIRECTORY_SEPARATOR)) . DIRECTORY_SEPARATOR;
		$this->view->files   = $options['log_files'];
	}
	
	public function importFolio(){
		$rmsportfolio = array(
				array(
						'ID' => 1,
						'Title' => 'Kanyin &amp; Pele',
						'LongDesc' => '&lt;p&gt;Kanyin and Pele wanted something unique, classy and off the chain for the wedding album. They had over 450 photos taken during wedding but could not find their ideal package that  showcase all the photographs they loved. 70 pages displaying 193 photographs.&lt;/p&gt;',
						'EventDate' => '2006-11-11 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'odiase1',
						'Location' => 'Bradford',
						'Pages' => 70,
						'Photos' => 193,
						'Remarks' => '',
						'FolioCategoryID' => '|13|3|1|4|',
						'SalesID' => 0,
						'ImageDir' => 'odiase1',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 2,
						'Title' => 'Alero weds Pele ',
						'LongDesc' => 'They had two volumes made which captured the events of the day as it unfolded, from the bride getting dressed to the couple leaving for their honey moon. The photobook includes captions and annotations, their  wedding vows , poems and excerpts from speeches delivered at the reception - 70 pages with 95 photographs.',
						'EventDate' => '2006-11-11 00:00:00',
						'EventTypeID' => 0,
						'ShortDesc' => 'odiase2',
						'Location' => 'Bradford',
						'Pages' => 70,
						'Photos' => 95,
						'Remarks' => '',
						'FolioCategoryID' => '|13|3|4|',
						'SalesID' => 0,
						'ImageDir' => 'odiase2',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 4,
						'Title' => 'Patricia &amp; Isaac',
						'LongDesc' => '&lt;p&gt;Mr. and Mrs. Madengu-Mangatu got married on the 16th of June 2007 at Hyde town hall, Hyde. A 78 page photobook displaying 259 photographs.&lt;/p&gt;',
						'EventDate' => '2007-06-16 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'madengu',
						'Location' => 'Manchester',
						'Pages' => 78,
						'Photos' => 259,
						'Remarks' => '&lt;p&gt;Our dream has always been to be trend and pacesetters in everything we do. 16 June 2007 was a mark and with the photographs that Rhema Studio took and produced, it is a mark that will be remembered. All our family and friends cannot stop looking at the photos, it has been by far the best work we have encounted in this day in age. Let us Authenticate Rhema Studios, they are legends in the making, a mark that will never be erased, totally and truely legends&lt;/p&gt;',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'madengu',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 3,
						'Title' => 'Rose weds Ugo',
						'LongDesc' => 'Mr. &amp; Mrs. Inyama got married in 2002 but 5 years down the line, they desired a more durable and presentable recollection of the most cherished moments of their lives. From the film negatives, we put together the artistic package which superseded their expectations. 50 pages with 124 photographs.',
						'EventDate' => '2002-08-24 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'inyama',
						'Location' => 'Nigeria',
						'Pages' => 50,
						'Photos' => 124,
						'Remarks' => 'Rhema Studio produces such a masterpiece, an amazing work of art. Your products and services have got our highest recommendation. I love our photobook. The picture selections were outstanding. Though the pictures were retrieved from negatives that were over over 4 yrs old, the outcome is so lovely.',
						'FolioCategoryID' => '|13|3|4|',
						'SalesID' => 0,
						'ImageDir' => 'inyama',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 5,
						'Title' => 'Itoro weds Edirin',
						'LongDesc' => 'The traditional wedding of Itoro and Edirin took place on the 9th of June 2007 while the military wedding and crossing of sword ceremony was held a week after, both in Nigeria. 70 page photobook displaying 171 photos.',
						'EventDate' => '2007-06-16 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'arigbe',
						'Location' => 'Nigeria',
						'Pages' => 70,
						'Photos' => 171,
						'Remarks' => '',
						'FolioCategoryID' => '|13|3|15|4|',
						'SalesID' => 0,
						'ImageDir' => 'arigbe',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 6,
						'Title' => 'Wedding Gift',
						'LongDesc' => 'A pictorial compilation of kind thoughts, encouragements and advices for the couple. A total of 25 contributions were received from family and friends highly respected by the bride/groom. A priceless wedding gift!',
						'EventDate' => '2007-07-14 00:00:00',
						'EventTypeID' => 5,
						'ShortDesc' => 'Susan Gardner&#039;s Wedding Gift',
						'Location' => 'Manchester',
						'Pages' => 50,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|1|',
						'SalesID' => 0,
						'ImageDir' => 'gardner',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 7,
						'Title' => 'Leslie &amp; Zainab',
						'LongDesc' => '&lt;p&gt;Mr. &amp;amp; Mrs Shyllon Wedded in April 1996. This photobook design was done from  photographs taken at the wedding and from images captured from video.&lt;/p&gt;',
						'EventDate' => '1996-04-10 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'shyllon',
						'Location' => 'Freetown',
						'Pages' => 50,
						'Photos' => 120,
						'Remarks' => '',
						'FolioCategoryID' => '|13|3|4|',
						'SalesID' => 0,
						'ImageDir' => 'shyllon',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 8,
						'Title' => '@ El-Shaddai',
						'LongDesc' => '&lt;p&gt;The wedding took place at El-Shaddai International Christian Centre Bradford. A 78-page photobook displaying 305 photographs. Viewing access restricted. Contact us for further details.&lt;/p&gt;',
						'EventDate' => '2007-07-14 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'Bakang weds Bayo',
						'Location' => 'Bradford',
						'Pages' => 78,
						'Photos' => 305,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'oniye',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 9,
						'Title' => 'Lihle weds Sipho ',
						'LongDesc' => 'The marriage of Mr. &amp; Mrs. Moyo took place at the marriage registry Heron House Manchester on the 25th of August 2007. A 30-page photobook with 81 photos on display.',
						'EventDate' => '2007-08-25 00:00:00',
						'EventTypeID' => 0,
						'ShortDesc' => 'Thembe weds Sipho',
						'Location' => 'Manchester',
						'Pages' => 30,
						'Photos' => 81,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'moyo1',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 10,
						'Title' => 'Thembe &amp; Sipho',
						'LongDesc' => '&lt;p&gt;The church blessing, reception and evening party of Mr. &amp;amp; Mrs. Moyo took place on the 8th of September 2007 at Hyde Town Hall, Hyde. A 78-page photobook displaying 281 photos.&lt;/p&gt;',
						'EventDate' => '2007-09-08 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'moyo2',
						'Location' => 'Hyde',
						'Pages' => 78,
						'Photos' => 281,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'moyo2',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 11,
						'Title' => 'Alero weds Edirin',
						'LongDesc' => 'Our Son\'s Wedding Photobook (OSW): Wedding photobook presented to the groom\'s family. 70 page photobook displaying 171 photos.',
						'EventDate' => '2007-06-09 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'arigbe2',
						'Location' => 'Lagos',
						'Pages' => 70,
						'Photos' => 171,
						'Remarks' => '',
						'FolioCategoryID' => '|3|',
						'SalesID' => 0,
						'ImageDir' => 'arigbe2',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 14,
						'Title' => 'Mmapula Tsietso',
						'LongDesc' => 'Rhema Studio Competition Winner - Photobook Star Prize was won by Mmapula. This is her personal photo collection. The photobook was designed from hard and digital copies of her album. A 50 page photobook displaying 124 photographs',
						'EventDate' => '2007-11-10 00:00:00',
						'EventTypeID' => 5,
						'ShortDesc' => 'tsietso',
						'Location' => 'Botswana',
						'Pages' => 50,
						'Photos' => 124,
						'Remarks' => '',
						'FolioCategoryID' => '|9|16|',
						'SalesID' => 0,
						'ImageDir' => 'tsietso',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 15,
						'Title' => 'Tim weds Joanna',
						'LongDesc' => 'Wedding Photobook of Mr. &amp; Mrs Grimshaw featuring 296 photographs in 78 pages. Event took place in Bradford, West Yorkshire on the 20th of October 2007.',
						'EventDate' => '2007-10-20 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'grimshaw',
						'Location' => 'Bradford',
						'Pages' => 78,
						'Photos' => 296,
						'Remarks' => '',
						'FolioCategoryID' => '|14|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'grimshaw',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 16,
						'Title' => 'Dominic &amp; Sally',
						'LongDesc' => '&lt;p&gt;The wedding of Mr. &amp;amp; Mrs. Shonhiwa took place on the 1st of December 2007 in Birmingham. Photographs taken at the wedding were presented in a 70-page photobook displaying 284 photographs.&lt;/p&gt;',
						'EventDate' => '2007-12-01 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'shonhiwa',
						'Location' => 'Birmingham',
						'Pages' => 70,
						'Photos' => 284,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'shonhiwa',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 17,
						'Title' => 'Brendan Mosweu',
						'LongDesc' => 'Personal Photo collection of Brendan Mosweu',
						'EventDate' => '2008-02-16 00:00:00',
						'EventTypeID' => 5,
						'ShortDesc' => 'mosweu',
						'Location' => 'Bostwana',
						'Pages' => 50,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|9|16|',
						'SalesID' => 0,
						'ImageDir' => 'mosweu',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 18,
						'Title' => 'Jaz &amp; Aswinder',
						'LongDesc' => '&lt;p&gt;This wedding photobook package of Mr. and Mrs Singh displays over 200 images in 78 pages. The photobook was designed from digital images and hard copies taken in 2007. It covers the Mendi, Choora, Jaggo and Mayian ceremonies consistent with a typical Sikh wedding .&lt;/p&gt;',
						'EventDate' => '2007-06-17 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'singh',
						'Location' => 'Birmingham',
						'Pages' => 78,
						'Photos' => 200,
						'Remarks' => '',
						'FolioCategoryID' => '|12|3|4|',
						'SalesID' => 0,
						'ImageDir' => 'singh',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 19,
						'Title' => 'Memory &amp; Haroon',
						'LongDesc' => '&lt;p&gt;A 98-page photobook of Memory and Haroon Rashid&#039;s wedding. The event took place on the 2nd of May 2008 at El-Shaddai International Christian Centre, Bradford. Photographs include getting ready shots, photos of wedding ceremony, reception and night party.&lt;/p&gt;',
						'EventDate' => '2008-05-02 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'rashid',
						'Location' => 'Bradford',
						'Pages' => 98,
						'Photos' => 210,
						'Remarks' => '&lt;p&gt;One of our favourite things about our photobook is the reaction it always gets. Our family and friends cannot believe that we have something so beautiful and professionally made which perfectly captures the best moments of our special day.&lt;/p&gt;
&lt;p&gt;The photobook is not just a photo-album. It&#039;s a work of art. Perfectly and attentively done right down to the finest detail, we are amazed at the quality.&lt;/p&gt;
&lt;p&gt;&lt;span id=&quot;authour&quot;&gt;Haroon and Memory Rashid&lt;/span&gt;&lt;/p&gt;',
						'FolioCategoryID' => '|12|14|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'rashid',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 20,
						'Title' => 'Dr. &amp; Mrs. Ajulo ',
						'LongDesc' => '&lt;p&gt;30 years and still counting in holy matrimony, the Ajulo&#039;s celebrate their pearl anniversary in Wakefield. A 98 page photobook displaying over 200 photos.&lt;/p&gt;',
						'EventDate' => '2008-07-19 00:00:00',
						'EventTypeID' => 7,
						'ShortDesc' => 'ajulo',
						'Location' => 'Wakefield',
						'Pages' => 98,
						'Photos' => 200,
						'Remarks' => '',
						'FolioCategoryID' => '|8|9|',
						'SalesID' => 1,
						'ImageDir' => 'ajulo',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 21,
						'Title' => 'Nkeiru weds Ilo',
						'LongDesc' => 'Wedding photobook of Mr. & Mrs. Akubuo. The event took place at the Immaculate Heart of Mary Catholic Church Leeds, West Yorkshire.',
						'EventDate' => '2008-08-16 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'akubuo',
						'Location' => 'Leeds',
						'Pages' => 98,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 2,
						'ImageDir' => 'akubuo',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 40,
						'Title' => 'Inspire 2007',
						'LongDesc' => 'El-Shaddai Bradford Women\'s Conference',
						'EventDate' => '2007-08-10 00:00:00',
						'EventTypeID' => 0,
						'ShortDesc' => 'Inspire 2007',
						'Location' => 'Bradford',
						'Pages' => 78,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|17|',
						'SalesID' => 0,
						'ImageDir' => 'inspire',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 41,
						'Title' => 'Inspire 2007',
						'LongDesc' => 'Inspire womens conference bradford',
						'EventDate' => '2007-08-10 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Inspire 08',
						'Location' => 'Bradford',
						'Pages' => 78,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|17|',
						'SalesID' => 0,
						'ImageDir' => 'inspire2',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 42,
						'Title' => 'Fouzia &amp; Joinal',
						'LongDesc' => '&lt;p&gt;This event took place over three days. The Medhi ceremony was done in Bradford on Friday 22nd August while the Nikah (wedding ceremony took place on Sunday, the 24th also in Bradford. The Walima (wedding reception) was hosted in Birmingham 3 days later.&lt;/p&gt;',
						'EventDate' => '2008-08-24 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'Fozia weds Joinal',
						'Location' => 'Bradford',
						'Pages' => 98,
						'Photos' => 319,
						'Remarks' => '',
						'FolioCategoryID' => '|12|2|4|',
						'SalesID' => 4,
						'ImageDir' => 'fouzia',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 43,
						'Title' => 'Change 2008',
						'LongDesc' => '',
						'EventDate' => '2008-07-23 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Change 2008',
						'Location' => 'London',
						'Pages' => 98,
						'Photos' => 188,
						'Remarks' => '',
						'FolioCategoryID' => '|2|17|',
						'SalesID' => 7,
						'ImageDir' => 'change08',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 44,
						'Title' => 'Reflection 2008',
						'LongDesc' => '',
						'EventDate' => '2008-05-23 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Reflection 2008',
						'Location' => 'London',
						'Pages' => 70,
						'Photos' => 108,
						'Remarks' => '',
						'FolioCategoryID' => '|2|17|',
						'SalesID' => 8,
						'ImageDir' => 'reflection08',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 45,
						'Title' => 'Glamour &amp; Style',
						'LongDesc' => '&lt;p&gt;El-shaddai Birmingham&#039;s 20s up cocktail party featuring cocktails and refreshments, evening entertainment and jazz band.&lt;/p&gt;',
						'EventDate' => '2008-10-25 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Glamour &amp; Style',
						'Location' => 'Birmingham',
						'Pages' => 0,
						'Photos' => 27,
						'Remarks' => '&lt;p&gt;Onsite&lt;/p&gt;',
						'FolioCategoryID' => '|18|',
						'SalesID' => 9,
						'ImageDir' => 'glamour',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 1),
				array(
						'ID' => 46,
						'Title' => 'Joanna &amp; Tim',
						'LongDesc' => '&lt;p&gt;Redesign of their wedding album on their 1st wedding anniversary&lt;/p&gt;',
						'EventDate' => '2007-10-20 00:00:00',
						'EventTypeID' => 7,
						'ShortDesc' => 'Joanna and Tim',
						'Location' => 'Bradford',
						'Pages' => 70,
						'Photos' => 180,
						'Remarks' => '',
						'FolioCategoryID' => '|14|2|4|',
						'SalesID' => 12,
						'ImageDir' => 'grimshaw2',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 47,
						'Title' => 'Cristina and Didier',
						'LongDesc' => '&lt;p&gt;Wedding ceremony &amp;nbsp;of Christina and Didier Penine which tool place on the 26th of July 2008 at Glenridding. A 98 page photobook showcasing 240 photographs.&lt;/p&gt;
&lt;p&gt;Compliments to Crash Taylor Photography.&lt;/p&gt;',
						'EventDate' => '2008-08-26 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'Cristina weds Didier',
						'Location' => 'Glenridding',
						'Pages' => 98,
						'Photos' => 240,
						'Remarks' => '&lt;p&gt;Thanks very much for the excellent work you did in putting together the photobooks for us, they look superb and they actually exceeded our expectations. The quality of the photobooks is outstanding, from the cover, to the interior design and to the thickness of the book itself all contributes to a fantastic memory of our wedding day.&lt;/p&gt;
&lt;p&gt;We found your company to be very professional and offering a very friendly service and we very much appreciated your constant contact and information on how the photobooks were developing and what the next steps were. We&#039;ll be sure to recommend people to use your services, and I&#039;m sure we will be in touch again in the future.&lt;/p&gt;',
						'FolioCategoryID' => '|14|3|4|',
						'SalesID' => 11,
						'ImageDir' => 'pennine',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 48,
						'Title' => 'Man08 Xmas Ball',
						'LongDesc' => '&lt;p&gt;ESICC Christmas Ball&lt;/p&gt;',
						'EventDate' => '2008-12-19 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Man08 Xmas Ball',
						'Location' => 'Manchester',
						'Pages' => 50,
						'Photos' => 75,
						'Remarks' => '',
						'FolioCategoryID' => '|18|',
						'SalesID' => 0,
						'ImageDir' => 'man08',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 49,
						'Title' => 'Brad08 Xmas Ball',
						'LongDesc' => '&lt;p&gt;ESICC Bradford Christmas Ball @ Leeds 2008&lt;/p&gt;',
						'EventDate' => '2008-12-20 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Brad08 Xmas Ball',
						'Location' => 'Leeds',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|18|',
						'SalesID' => 0,
						'ImageDir' => 'brad08',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 1),
				array(
						'ID' => 50,
						'Title' => 'Brad07 Xmas Ball',
						'LongDesc' => '&lt;p&gt;ESICC Christmas Ball @ Leeds Marriot Hotel 2007&lt;/p&gt;',
						'EventDate' => '2007-12-12 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Brad07 Xmas Ball',
						'Location' => 'Leeds',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|18|',
						'SalesID' => 0,
						'ImageDir' => 'brad07',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 1),
				array(
						'ID' => 51,
						'Title' => 'Man 20up',
						'LongDesc' => '&lt;p&gt;ESICC S0&#039;s up launch Manchester&lt;/p&gt;',
						'EventDate' => '2007-04-21 16:40:00',
						'EventTypeID' => 0,
						'ShortDesc' => '20&#039;s Up Man07',
						'Location' => 'Manchester',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|18|',
						'SalesID' => 0,
						'ImageDir' => 'man20up07',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 52,
						'Title' => 'CFP Dec 07',
						'LongDesc' => '&lt;p&gt;ESICC Bradford Created For Praise event featuring Ron Kenoly in concert&lt;/p&gt;',
						'EventDate' => '2007-12-01 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'CFP Dec 07',
						'Location' => 'Bradford',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|19|',
						'SalesID' => 0,
						'ImageDir' => 'cfpdec07',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 53,
						'Title' => 'Kate&#039;s 90th',
						'LongDesc' => '&lt;p&gt;Kates 90th Birthday Celebration&lt;/p&gt;',
						'EventDate' => '2008-09-20 00:00:00',
						'EventTypeID' => 2,
						'ShortDesc' => 'Kate&#039;s 90th',
						'Location' => 'Coventry',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|8|20|',
						'SalesID' => 0,
						'ImageDir' => 'kate',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 54,
						'Title' => 'Man08 Faith',
						'LongDesc' => '&lt;p&gt;ESICC Manchester&#039;s faith conference 2008&lt;/p&gt;',
						'EventDate' => '2008-09-20 07:31:33',
						'EventTypeID' => 8,
						'ShortDesc' => 'Faith Conf 08',
						'Location' => 'Manchester',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|17|',
						'SalesID' => 0,
						'ImageDir' => 'manfc08',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 55,
						'Title' => 'CFP Mar 2007',
						'LongDesc' => '&lt;p&gt;ESICC Bradford - Created For Praise event featuring Noel Robinson and the NU Band&lt;/p&gt;',
						'EventDate' => '2007-03-04 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'CFP Mar 07',
						'Location' => 'Bradford',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|19|',
						'SalesID' => 0,
						'ImageDir' => 'cfpmar07',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 56,
						'Title' => 'CFP Oct 08',
						'LongDesc' => '&lt;p&gt;ESICC Bradford - Created For Praise event featuring the world renowned gospel artist Muyiwa&lt;/p&gt;',
						'EventDate' => '2008-11-09 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'CFP Oct 08',
						'Location' => 'Bradford',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|19|',
						'SalesID' => 0,
						'ImageDir' => 'cfpoct08',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 57,
						'Title' => 'Victory 07',
						'LongDesc' => '&lt;p&gt;ESICC Bradfords - Victory Conference and Created for Praise event featuring the world&#039;s famous gospel artist and legent Ron Kenoly&lt;/p&gt;',
						'EventDate' => '2007-07-15 00:00:00',
						'EventTypeID' => 8,
						'ShortDesc' => 'Victory 07',
						'Location' => 'Bradford',
						'Pages' => 0,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|17|19|',
						'SalesID' => 0,
						'ImageDir' => 'vic07',
						'Active' => 1,
						'Restricted' => 1,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 58,
						'Title' => 'Omare&#039;s 50th',
						'LongDesc' => '&lt;p&gt;50th Birthday celebration&lt;/p&gt;',
						'EventDate' => '2008-09-12 00:00:00',
						'EventTypeID' => 2,
						'ShortDesc' => 'Omare&#039;s 50th',
						'Location' => 'Benin',
						'Pages' => 18,
						'Photos' => 47,
						'Remarks' => '',
						'FolioCategoryID' => '|8|20|3|1|',
						'SalesID' => 0,
						'ImageDir' => 'omare',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 59,
						'Title' => 'Her Birthday',
						'LongDesc' => '&lt;p&gt;Marking the her birthday in style - Dr. M Benka-Coker&lt;/p&gt;',
						'EventDate' => '2008-09-09 00:00:00',
						'EventTypeID' => 2,
						'ShortDesc' => 'Her Birthday',
						'Location' => 'Benin',
						'Pages' => 22,
						'Photos' => 97,
						'Remarks' => '',
						'FolioCategoryID' => '|8|20|3|',
						'SalesID' => 0,
						'ImageDir' => 'bcoker',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 60,
						'Title' => 'Zandile &amp; Melusi',
						'LongDesc' => '&lt;p&gt;Wedding of Zandile and Melusi in Manchester&lt;/p&gt;',
						'EventDate' => '2007-08-25 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'Zandile &amp; Melusi',
						'Location' => 'Ardwick',
						'Pages' => 0,
						'Photos' => 210,
						'Remarks' => '',
						'FolioCategoryID' => '|13|4|',
						'SalesID' => 0,
						'ImageDir' => 'zandile',
						'Active' => 0,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 61,
						'Title' => 'Pauline &amp; Robert',
						'LongDesc' => '&lt;p&gt;Wedding ofPauline and Robert George in leeds 30th August 2008&lt;/p&gt;',
						'EventDate' => '2008-08-30 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'Pauline &amp; Robert',
						'Location' => 'Leeds',
						'Pages' => 0,
						'Photos' => 250,
						'Remarks' => '',
						'FolioCategoryID' => '|4|',
						'SalesID' => 3,
						'ImageDir' => 'george',
						'Active' => 0,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 62,
						'Title' => 'Thuli weds Gerald',
						'LongDesc' => '&lt;p&gt;Wedding of Thuli and Gerald in Bradford - 5th July 2008&lt;/p&gt;',
						'EventDate' => '2008-07-05 00:00:00',
						'EventTypeID' => 1,
						'ShortDesc' => 'Thuli &amp; Gerald',
						'Location' => 'Bradford',
						'Pages' => 0,
						'Photos' => 195,
						'Remarks' => '',
						'FolioCategoryID' => '|18|4|',
						'SalesID' => 0,
						'ImageDir' => 'thuli',
						'Active' => 0,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 63,
						'Title' => 'Suki &amp; Sukhi',
						'LongDesc' => '&lt;p&gt;Sikh wedding of Suki and Sukhi in Bradford 27 - 28 September 2008&lt;/p&gt;',
						'EventDate' => '2008-09-28 07:37:34',
						'EventTypeID' => 1,
						'ShortDesc' => 'Suki weds Sukhi',
						'Location' => 'Bradford',
						'Pages' => 98,
						'Photos' => 185,
						'Remarks' => '',
						'FolioCategoryID' => '|12|2|4|',
						'SalesID' => 5,
						'ImageDir' => 'suki',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 64,
						'Title' => 'Cathie weds Isaac',
						'LongDesc' => '&lt;p&gt;Wedding of Catherine and Isaac took place in Delta State, Nigeria&lt;/p&gt;',
						'EventDate' => '2009-04-18 08:39:28',
						'EventTypeID' => 1,
						'ShortDesc' => 'Cathie weds Isaac',
						'Location' => 'Nigeria',
						'Pages' => 58,
						'Photos' => 70,
						'Remarks' => '',
						'FolioCategoryID' => '|13|3|4|',
						'SalesID' => 0,
						'ImageDir' => 'odiase3',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 65,
						'Title' => 'Kevin &amp; Kete',
						'LongDesc' => '&lt;p&gt;Wedding of Mr. and Mrs. Kevin Fatinikun took place on the 30th May 2009 at the El-Shaddai International Christian Center Bradford, West Yorkshire.&lt;/p&gt;',
						'EventDate' => '2009-05-30 09:23:27',
						'EventTypeID' => 1,
						'ShortDesc' => 'Kevin weds Mamokete',
						'Location' => 'Bradford',
						'Pages' => 98,
						'Photos' => 180,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'kevin',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 66,
						'Title' => 'Vince &amp; Nkiru',
						'LongDesc' => '&lt;p&gt;Traditional and Christian wedding ceremonies of Mr. and Mrs. Vincent Omenukwa.&lt;/p&gt;',
						'EventDate' => '2008-12-29 09:55:52',
						'EventTypeID' => 1,
						'ShortDesc' => 'Vincent and Nkiru',
						'Location' => 'Nigeria',
						'Pages' => 78,
						'Photos' => 120,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'omenukwa',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 67,
						'Title' => 'Kemi is 40',
						'LongDesc' => '&lt;p&gt;The 40th Birthday celebration of Mrs. Obayelu took place on the 4th of April 2009&lt;/p&gt;',
						'EventDate' => '2009-04-04 10:12:40',
						'EventTypeID' => 2,
						'ShortDesc' => 'Kemi&#039;s 40th',
						'Location' => 'Birmingham',
						'Pages' => 66,
						'Photos' => 105,
						'Remarks' => '',
						'FolioCategoryID' => '|8|20|2|9|16|',
						'SalesID' => 0,
						'ImageDir' => 'obayelu',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 0,
						'ForSale' => 0),
				array(
						'ID' => 68,
						'Title' => 'Chido &amp; Vanessa',
						'LongDesc' => '&lt;p&gt;Chido and Vanessa got married at El-Shaddai International Christian Center Bradford, West Yorkshire on the 1st of August 2009. A fruitful union it was!&lt;/p&gt;',
						'EventDate' => '2009-08-01 10:27:35',
						'EventTypeID' => 1,
						'ShortDesc' => 'Chido &amp; Vanessa',
						'Location' => 'Bradford',
						'Pages' => 98,
						'Photos' => 195,
						'Remarks' => '',
						'FolioCategoryID' => '|13|2|4|',
						'SalesID' => 0,
						'ImageDir' => 'gideon',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0),
				array(
						'ID' => 69,
						'Title' => 'Bola and Tunde',
						'LongDesc' => '',
						'EventDate' => '2010-08-14 01:05:37',
						'EventTypeID' => 1,
						'ShortDesc' => 'Bola weds Tunde',
						'Location' => 'Manchester',
						'Pages' => 98,
						'Photos' => 0,
						'Remarks' => '',
						'FolioCategoryID' => '|13|4|',
						'SalesID' => 0,
						'ImageDir' => 'oyinloye',
						'Active' => 1,
						'Restricted' => 0,
						'Disp' => 1,
						'ForSale' => 0));
				foreach($rmsportfolio as $item){
					$event = array();
					$f = array();

					$event['title'] = html_entity_decode($item['Title']);
					$event['start_at'] = $item['EventDate'];
					$event['end_at']   = date(DB_DATE_FORMAT, strtotime($event['start_at']) + (24*60*60) - 1);
					$event['event_type_id'] = 1;
					$event['user_id'] = 1;
					$event['is_active'] = 1;
					$event['keyword']   = $item['ImageDir'];
					$event['location']  = $item['Location'];
					$event['content'] = strip_tags(html_entity_decode($item['LongDesc']));

					$ev = new Admin_Model_Event();
					$ev->fromArray($event);
					$ev->save();

					$f['title'] = html_entity_decode($item['Title']);
					$f['page_count']  = $item['Pages'];
					$f['photo_count'] = $item['Photos'];
					$f['description'] = strip_tags(html_entity_decode($item['ShortDesc']));
					$f['role_id'] = 1;
					$f['event_id'] = $ev->id;
					$f['created_at'] = $item['EventDate'];
					$f['keyword']   = $item['ImageDir'];
					$f['note']   = strip_tags(html_entity_decode($item['Remarks']));

					$p = new Admin_Model_Portfolio();
					$p->fromArray($f);
					$p->save();
				}
	}
	public function importComments(){
		/**
		 * Export to PHP Array plugin for PHPMyAdmin
		 * @author Geoffray Warnants
		 * @version 0.2b
		 */

		//
		// Database "rhemastu_rmsadmin"
		//


		// rhemastu_rmsadmin.rmsguestbook
		$rmsguestbook = array(
				array(
						'ID' => 1,
						'Name' => 'michael robinson',
						'Town' => 'Bradford',
						'Email' => 'miker619&#64;msn&#46;com',
						'Url' => '',
						'Comment' => 'Hi Guys I think your work is incredible. It is so excellent I think you should talk to the right people about developing the business. What you do is better than anything else I\'ve seen. At all. Anywhere. Ever!!',
						'Added' => '2007-07-23 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '89.213.41.98
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 2,
						'Name' => 'Haroon Rashid',
						'Town' => 'Bradford',
						'Email' => 'haroon76&#64;hotmail&#46;co&#46;uk',
						'Url' => '',
						'Comment' => 'I\'ve checked out your website. Excellent work! I especially like the \'real moments\' you capture when no one knows you\'re shooting them. Really like the Ron Kenoly shots too.<br /><br />Keep up the good work!',
						'Added' => '2007-07-19 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '81.159.35.97
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 3,
						'Name' => 'Tapiwa Ngoma',
						'Town' => 'Manchester',
						'Email' => 'Tapie08&#64;hotmail&#46;com',
						'Url' => '',
						'Comment' => 'hmm absolutely amazing piece of work..l was totally mesmerised by the sheer expertise shown by Rhema Studio..lm not getting married anytym soon but be assured of doin my pictures at my wedding..great work absolutely smashing!! <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2007-07-17 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '84.13.116.31
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 4,
						'Name' => 'Osa Erebor',
						'Town' => 'Nigeria',
						'Email' => 'debosa652&#64;yahoo&#46;com',
						'Url' => '',
						'Comment' => 'Hi, i think this is a wonderful site filled with innovative ideas, inspiring stuff and great services. Please keep up the good work.',
						'Added' => '2007-07-17 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '41.220.65.107
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 5,
						'Name' => 'justine James',
						'Town' => 'bristol',
						'Email' => 'kool2bme&#64;netpiper&#46;com',
						'Url' => '',
						'Comment' => 'execellent web and pics will give my recommendation to my pals, ps God\'s blessing to you all',
						'Added' => '2007-07-13 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '82.71.35.114
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 6,
						'Name' => 'Rose Inyama',
						'Town' => 'Manchester',
						'Email' => 'ucheinyama&#64;hotmail&#46;com',
						'Url' => '',
						'Comment' => 'Rhema Studio produces such a masterpiece, an amazing work of art. Your products and services have got our highest recommendation. I love our photobook. The picture selections were outstanding. Though the pictures were retrieved from negatives that were over over 4 yrs old, the outcome is so lovely.',
						'Added' => '2007-07-10 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '86.145.211.31
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 7,
						'Name' => 'Thembi Ncube',
						'Town' => 'Manchester',
						'Email' => '',
						'Url' => '',
						'Comment' => 'I can\'t help checking out your website everyday, its just too good. May God make your multi millionaires through your photography business. I\'ve spent an hour looking at the photos.',
						'Added' => '2007-07-10 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '86.145.211.31
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 8,
						'Name' => 'Patricia Madengu',
						'Town' => 'Stockport Cheshire',
						'Email' => 'pat-ike&#64;tiscali&#46;co&#46;uk',
						'Url' => '',
						'Comment' => 'Our dream has always been to be trend and pacesetters in everything we do. 16 June 2007 was a mark and with the photographs that Rhema Studio took and produced, it is a mark that will be remembered. All our family and friends cannot stop looking at the photos, it has been by far the best work we have encounted in this day in age. Let us Authenticate Rhema Studios, they are legends in the making, a mark that will never be erased, totally and truely legends',
						'Added' => '2007-07-09 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '88.104.251.115
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 9,
						'Name' => 'Abraham Koffi',
						'Town' => 'Ivory Coast',
						'Email' => 'abrahamkoffi_1&#64;yahoo&#46;co&#46;uk',
						'Url' => '',
						'Comment' => 'You are doing a fantastic, wonderful...job. It\'s just wow!!!<br />This is state of the art design and services. May the Good Lord grant you more wisdom, knowledge and skills!<br />I would strongly recommend Rhema Studio to anyone.<br />Well done, keep it up!',
						'Added' => '2007-07-09 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '86.140.91.10
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 10,
						'Name' => 'Pepiyani Zache',
						'Town' => 'Berlin',
						'Email' => 'sitat3&#64;yahoo&#46;com',
						'Url' => '',
						'Comment' => 'Rhemastudio has an excellent site your design style is contemporary and fresh and most importantly is you offer bespoke service.<br />kudos to you and keep up the faboulous job <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2007-07-04 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '81.149.18.181
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 11,
						'Name' => 'Bukkie Adeola',
						'Town' => 'Manchester',
						'Email' => 'maryjayng&#64;yahoo&#46;com',
						'Url' => '',
						'Comment' => 'Rhema studio definitely rocks!the creativity is mind blowing and the sky is not the limit but a starting point!Before we all know it u\'l b up there unparalled!More power to your elbow!',
						'Added' => '2007-07-04 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '90.195.23.33
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 12,
						'Name' => 'Eyako Klu',
						'Town' => 'Manchester',
						'Email' => '',
						'Url' => '',
						'Comment' => 'I think I am most impressed by the quality of work and the service.....super.....I dont know how u do it....its awesome!',
						'Added' => '2007-07-03 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '82.21.39.199
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 13,
						'Name' => 'Olanike Adebayo',
						'Town' => 'Manchester,UK(The litehouse)',
						'Email' => 'naikiadex&#64;yahoo&#46;co&#46;uk',
						'Url' => '',
						'Comment' => 'It\'s not just that the website is fantastic but the quality of services we at the litehouse recieve from Rhemastudios is not only excellent but also,bespoke.The photobook I believe is a must for everyone whowants to keep the memories of great events in their lives for the longest period possible.Keep the torch burning.Cheers,Olanike',
						'Added' => '2007-07-03 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '86.145.210.39
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 14,
						'Name' => 'Mamie Egigba',
						'Town' => '',
						'Email' => '',
						'Url' => '',
						'Comment' => 'Pictures are top notch.... very professional. one of the best i have seen.... keep up the good work <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/ylsuper.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2007-07-02 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '195.93.21.100
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 15,
						'Name' => 'Emem Archibond',
						'Town' => 'Bradford',
						'Email' => 'ememarchibong&#64;yahoo&#46;co&#46;uk',
						'Url' => '',
						'Comment' => 'I am loving ur site and I will be sure to contact u when I\'ll be requiring ur services in the future <img src=\"images/smiley/icon_smile.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/icon_smile.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2007-07-02 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '80.44.88.179
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 16,
						'Name' => 'Abena Britwum',
						'Town' => 'Ghana',
						'Email' => 'ladyabena&#64;yahoo&#46;com',
						'Url' => '',
						'Comment' => 'Hi Rhemastudios.<br /><br />Your work is absolutely fantastic. Keep up the good work.<br /><br />Abena <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2007-06-30 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '90.198.191.203
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 17,
						'Name' => 'Fola Ogunnusi',
						'Town' => 'Stockport',
						'Email' => '',
						'Url' => '',
						'Comment' => 'The quality and finishing of Rhema pictures are fantastic. I would highly recommend anyone who wants quality and authentic pictures to patronise RHEMA STUDIO.<br /><br />As for me and my family, Rhema Studio is the answer for our family photographs.',
						'Added' => '2007-06-30 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '81.149.18.181
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 18,
						'Name' => 'Bola Adeola',
						'Town' => 'Manchester',
						'Email' => 'bolaadeola3&#64;yahoo&#46;com',
						'Url' => '',
						'Comment' => 'The products that I have seen of Rhemastudio is absolutely outstanding; well arranged, clear, and strategic pictures!!! I\'ll definitely recommend Rhemastudio to all, for very good pictures!!! Weldone!!!!!!!!! <img src=\"images/smiley/icon_smile.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2007-06-26 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '90.201.14.30
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 19,
						'Name' => 'Yemi Makinde',
						'Town' => 'Manchester',
						'Email' => 'mankind4life&#64;hotmail&#46;co&#46;uk',
						'Url' => '',
						'Comment' => 'You have been a very diligent man in what you do and therefore you won\'t stand before mere men. And you works will really go far and wide. See you at the  top. <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />  <img src=\"images/smiley/yelclap.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2007-06-26 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '86.139.34.27
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 20,
						'Name' => 'Mmapula Tsietso',
						'Town' => 'Bradford',
						'Email' => 'maptee&#64;yahoo&#46;co&#46;uk',
						'Url' => '',
						'Comment' => 'i think you\'re doing a very good job..the pictures and just the arrangement of the photbook is beautiful..out of this world. I like it.keep it up!',
						'Added' => '2007-06-26 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '84.9.192.202
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 21,
						'Name' => 'Corina Philipescu',
						'Town' => '',
						'Email' => '',
						'Url' => '',
						'Comment' => 'The job that you are doing is great and really something people appreciate. Keep up the good work.',
						'Added' => '2007-06-26 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '84.70.91.68
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 22,
						'Name' => 'Michael Jones',
						'Town' => 'Bradford',
						'Email' => 'michael&#46;jones&#64;emprorecruitment&#46;com',
						'Url' => '',
						'Comment' => 'You are doing a great job I like your product, keep doing what you doing and thank you for your help. Regards MJ',
						'Added' => '2007-06-26 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '86.140.16.126
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 23,
						'Name' => 'Alero Coker',
						'Town' => 'bradford',
						'Email' => 'kluxy4life&#64;hotmail&#46;com',
						'Url' => '',
						'Comment' => 'Rhemastudio is absolutely wonderful. exquisite work, done with precision and passion. Pele is really talented. great stuff. keep it up, mate',
						'Added' => '2007-06-25 00:00:00',
						'IsPrivate' => 0,
						'IpAddress' => '86.140.16.126
',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''),
				array(
						'ID' => 24,
						'Name' => 'Sitty Fugede',
						'Town' => 'Coventry',
						'Email' => '',
						'Url' => '',
						'Comment' => 'What a proffessional website and the quality is just second to none. Well done and keep up the great work, will dedinately recommend.. <img src=\"images/smiley/icon_smile.gif\" border=\"0\" alt=\"\" />',
						'Added' => '2010-05-20 16:49:14',
						'IsPrivate' => 0,
						'IpAddress' => '90.200.218.160',
						'Reply' => 0,
						'Title' => '',
						'ShortDesc' => ''));

		//pd($rmsguestbook);
		$done = array();
		foreach($rmsguestbook as $com){
			$com['Email'] = $com['Email'] ? $com['Email'] : $com['Name'];
			if(! isset($done[$com['Email']])){
				list($user['firstname'], $user['lastname']) = explode(' ', $com['Name']);
				$user['email'] = html_entity_decode($com['Email']);
				$user['username'] = $user['password'] = $user['email'];
				$arr['comment'] = strip_tags($com['Comment']);
				$arr['created_at'] = $com['Added'];
				$arr['ip_address'] = $com['IpAddress'];
				$arr['rating'] = rand(4, 5);

				$uObject = new Admin_Model_User();
				$uObject->fromArray($user);
				$uObject->save();

				$arr['author'] = $uObject->id;
				$comObj = new Admin_Model_PortfolioComment();
				$comObj->fromArray($arr);
				$comObj->save();
			}

		}
	}

}